// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package inout

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRoleRequestV1 struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleRequestV1) Reset()         { *m = CreateRoleRequestV1{} }
func (m *CreateRoleRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRequestV1) ProtoMessage()    {}
func (*CreateRoleRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{0}
}
func (m *CreateRoleRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleRequestV1.Unmarshal(m, b)
}
func (m *CreateRoleRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateRoleRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleRequestV1.Merge(dst, src)
}
func (m *CreateRoleRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateRoleRequestV1.Size(m)
}
func (m *CreateRoleRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleRequestV1 proto.InternalMessageInfo

func (m *CreateRoleRequestV1) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateRoleBadRequestV1 struct {
	Title                []string `protobuf:"bytes,1,rep,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleBadRequestV1) Reset()         { *m = CreateRoleBadRequestV1{} }
func (m *CreateRoleBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateRoleBadRequestV1) ProtoMessage()    {}
func (*CreateRoleBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{1}
}
func (m *CreateRoleBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleBadRequestV1.Unmarshal(m, b)
}
func (m *CreateRoleBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateRoleBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleBadRequestV1.Merge(dst, src)
}
func (m *CreateRoleBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateRoleBadRequestV1.Size(m)
}
func (m *CreateRoleBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleBadRequestV1 proto.InternalMessageInfo

func (m *CreateRoleBadRequestV1) GetTitle() []string {
	if m != nil {
		return m.Title
	}
	return nil
}

type GetRoleResponseV1 struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleResponseV1) Reset()         { *m = GetRoleResponseV1{} }
func (m *GetRoleResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetRoleResponseV1) ProtoMessage()    {}
func (*GetRoleResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{2}
}
func (m *GetRoleResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleResponseV1.Unmarshal(m, b)
}
func (m *GetRoleResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleResponseV1.Marshal(b, m, deterministic)
}
func (dst *GetRoleResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleResponseV1.Merge(dst, src)
}
func (m *GetRoleResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetRoleResponseV1.Size(m)
}
func (m *GetRoleResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleResponseV1 proto.InternalMessageInfo

func (m *GetRoleResponseV1) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetRoleResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *GetRoleResponseV1) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ListRoleResponseV1 struct {
	Data                 []*GetRoleResponseV1 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListRoleResponseV1) Reset()         { *m = ListRoleResponseV1{} }
func (m *ListRoleResponseV1) String() string { return proto.CompactTextString(m) }
func (*ListRoleResponseV1) ProtoMessage()    {}
func (*ListRoleResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{3}
}
func (m *ListRoleResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoleResponseV1.Unmarshal(m, b)
}
func (m *ListRoleResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoleResponseV1.Marshal(b, m, deterministic)
}
func (dst *ListRoleResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoleResponseV1.Merge(dst, src)
}
func (m *ListRoleResponseV1) XXX_Size() int {
	return xxx_messageInfo_ListRoleResponseV1.Size(m)
}
func (m *ListRoleResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoleResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoleResponseV1 proto.InternalMessageInfo

func (m *ListRoleResponseV1) GetData() []*GetRoleResponseV1 {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateUserRoleRequestV1 struct {
	UserID               []byte   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	RoleID               []byte   `protobuf:"bytes,2,opt,name=roleID,proto3" json:"roleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRoleRequestV1) Reset()         { *m = CreateUserRoleRequestV1{} }
func (m *CreateUserRoleRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserRoleRequestV1) ProtoMessage()    {}
func (*CreateUserRoleRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{4}
}
func (m *CreateUserRoleRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRoleRequestV1.Unmarshal(m, b)
}
func (m *CreateUserRoleRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRoleRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserRoleRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRoleRequestV1.Merge(dst, src)
}
func (m *CreateUserRoleRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserRoleRequestV1.Size(m)
}
func (m *CreateUserRoleRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRoleRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRoleRequestV1 proto.InternalMessageInfo

func (m *CreateUserRoleRequestV1) GetUserID() []byte {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *CreateUserRoleRequestV1) GetRoleID() []byte {
	if m != nil {
		return m.RoleID
	}
	return nil
}

type CreateUserRoleBadRequestV1 struct {
	UserID               []string `protobuf:"bytes,1,rep,name=userID,proto3" json:"userID,omitempty"`
	RoleID               []string `protobuf:"bytes,2,rep,name=roleID,proto3" json:"roleID,omitempty"`
	Errors               []string `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRoleBadRequestV1) Reset()         { *m = CreateUserRoleBadRequestV1{} }
func (m *CreateUserRoleBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserRoleBadRequestV1) ProtoMessage()    {}
func (*CreateUserRoleBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{5}
}
func (m *CreateUserRoleBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRoleBadRequestV1.Unmarshal(m, b)
}
func (m *CreateUserRoleBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRoleBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserRoleBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRoleBadRequestV1.Merge(dst, src)
}
func (m *CreateUserRoleBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserRoleBadRequestV1.Size(m)
}
func (m *CreateUserRoleBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRoleBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRoleBadRequestV1 proto.InternalMessageInfo

func (m *CreateUserRoleBadRequestV1) GetUserID() []string {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *CreateUserRoleBadRequestV1) GetRoleID() []string {
	if m != nil {
		return m.RoleID
	}
	return nil
}

func (m *CreateUserRoleBadRequestV1) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type CreateUserRolesRequestV1 struct {
	UserRoles            []*CreateUserRoleRequestV1 `protobuf:"bytes,1,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreateUserRolesRequestV1) Reset()         { *m = CreateUserRolesRequestV1{} }
func (m *CreateUserRolesRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserRolesRequestV1) ProtoMessage()    {}
func (*CreateUserRolesRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{6}
}
func (m *CreateUserRolesRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRolesRequestV1.Unmarshal(m, b)
}
func (m *CreateUserRolesRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRolesRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserRolesRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRolesRequestV1.Merge(dst, src)
}
func (m *CreateUserRolesRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserRolesRequestV1.Size(m)
}
func (m *CreateUserRolesRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRolesRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRolesRequestV1 proto.InternalMessageInfo

func (m *CreateUserRolesRequestV1) GetUserRoles() []*CreateUserRoleRequestV1 {
	if m != nil {
		return m.UserRoles
	}
	return nil
}

type CreateUserRolesBadRequestV1 struct {
	Errors               []*CreateUserRoleBadRequestV1 `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CreateUserRolesBadRequestV1) Reset()         { *m = CreateUserRolesBadRequestV1{} }
func (m *CreateUserRolesBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserRolesBadRequestV1) ProtoMessage()    {}
func (*CreateUserRolesBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{7}
}
func (m *CreateUserRolesBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRolesBadRequestV1.Unmarshal(m, b)
}
func (m *CreateUserRolesBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRolesBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserRolesBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRolesBadRequestV1.Merge(dst, src)
}
func (m *CreateUserRolesBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserRolesBadRequestV1.Size(m)
}
func (m *CreateUserRolesBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRolesBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRolesBadRequestV1 proto.InternalMessageInfo

func (m *CreateUserRolesBadRequestV1) GetErrors() []*CreateUserRoleBadRequestV1 {
	if m != nil {
		return m.Errors
	}
	return nil
}

type GetUserRoleResponseV1 struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	UserID               []byte   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	RoleID               []byte   `protobuf:"bytes,4,opt,name=roleID,proto3" json:"roleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRoleResponseV1) Reset()         { *m = GetUserRoleResponseV1{} }
func (m *GetUserRoleResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetUserRoleResponseV1) ProtoMessage()    {}
func (*GetUserRoleResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{8}
}
func (m *GetUserRoleResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRoleResponseV1.Unmarshal(m, b)
}
func (m *GetUserRoleResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRoleResponseV1.Marshal(b, m, deterministic)
}
func (dst *GetUserRoleResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRoleResponseV1.Merge(dst, src)
}
func (m *GetUserRoleResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetUserRoleResponseV1.Size(m)
}
func (m *GetUserRoleResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRoleResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRoleResponseV1 proto.InternalMessageInfo

func (m *GetUserRoleResponseV1) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetUserRoleResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *GetUserRoleResponseV1) GetUserID() []byte {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *GetUserRoleResponseV1) GetRoleID() []byte {
	if m != nil {
		return m.RoleID
	}
	return nil
}

type ListUserRolesResponseV1 struct {
	Data                 []*GetUserRoleResponseV1 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ListUserRolesResponseV1) Reset()         { *m = ListUserRolesResponseV1{} }
func (m *ListUserRolesResponseV1) String() string { return proto.CompactTextString(m) }
func (*ListUserRolesResponseV1) ProtoMessage()    {}
func (*ListUserRolesResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{9}
}
func (m *ListUserRolesResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRolesResponseV1.Unmarshal(m, b)
}
func (m *ListUserRolesResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRolesResponseV1.Marshal(b, m, deterministic)
}
func (dst *ListUserRolesResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRolesResponseV1.Merge(dst, src)
}
func (m *ListUserRolesResponseV1) XXX_Size() int {
	return xxx_messageInfo_ListUserRolesResponseV1.Size(m)
}
func (m *ListUserRolesResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRolesResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRolesResponseV1 proto.InternalMessageInfo

func (m *ListUserRolesResponseV1) GetData() []*GetUserRoleResponseV1 {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateEmailRequestV1 struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	UserID               []byte   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailRequestV1) Reset()         { *m = CreateEmailRequestV1{} }
func (m *CreateEmailRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailRequestV1) ProtoMessage()    {}
func (*CreateEmailRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{10}
}
func (m *CreateEmailRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailRequestV1.Unmarshal(m, b)
}
func (m *CreateEmailRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailRequestV1.Merge(dst, src)
}
func (m *CreateEmailRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailRequestV1.Size(m)
}
func (m *CreateEmailRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailRequestV1 proto.InternalMessageInfo

func (m *CreateEmailRequestV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateEmailRequestV1) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateEmailRequestV1) GetUserID() []byte {
	if m != nil {
		return m.UserID
	}
	return nil
}

type CreateEmailBadRequestV1 struct {
	Email                []string `protobuf:"bytes,1,rep,name=email,proto3" json:"email,omitempty"`
	Code                 []string `protobuf:"bytes,2,rep,name=code,proto3" json:"code,omitempty"`
	UserId               []string `protobuf:"bytes,3,rep,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailBadRequestV1) Reset()         { *m = CreateEmailBadRequestV1{} }
func (m *CreateEmailBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailBadRequestV1) ProtoMessage()    {}
func (*CreateEmailBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{11}
}
func (m *CreateEmailBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailBadRequestV1.Unmarshal(m, b)
}
func (m *CreateEmailBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailBadRequestV1.Merge(dst, src)
}
func (m *CreateEmailBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailBadRequestV1.Size(m)
}
func (m *CreateEmailBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailBadRequestV1 proto.InternalMessageInfo

func (m *CreateEmailBadRequestV1) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *CreateEmailBadRequestV1) GetCode() []string {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CreateEmailBadRequestV1) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

type CreateEmailResponseV1 struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	UserID               []byte   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailResponseV1) Reset()         { *m = CreateEmailResponseV1{} }
func (m *CreateEmailResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailResponseV1) ProtoMessage()    {}
func (*CreateEmailResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{12}
}
func (m *CreateEmailResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailResponseV1.Unmarshal(m, b)
}
func (m *CreateEmailResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailResponseV1.Merge(dst, src)
}
func (m *CreateEmailResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailResponseV1.Size(m)
}
func (m *CreateEmailResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailResponseV1 proto.InternalMessageInfo

func (m *CreateEmailResponseV1) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CreateEmailResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CreateEmailResponseV1) GetUserID() []byte {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *CreateEmailResponseV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateEmailConfirmationRequestV1 struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailConfirmationRequestV1) Reset()         { *m = CreateEmailConfirmationRequestV1{} }
func (m *CreateEmailConfirmationRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailConfirmationRequestV1) ProtoMessage()    {}
func (*CreateEmailConfirmationRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{13}
}
func (m *CreateEmailConfirmationRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailConfirmationRequestV1.Unmarshal(m, b)
}
func (m *CreateEmailConfirmationRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailConfirmationRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailConfirmationRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailConfirmationRequestV1.Merge(dst, src)
}
func (m *CreateEmailConfirmationRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailConfirmationRequestV1.Size(m)
}
func (m *CreateEmailConfirmationRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailConfirmationRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailConfirmationRequestV1 proto.InternalMessageInfo

func (m *CreateEmailConfirmationRequestV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateEmailConfirmationBadRequestV1 struct {
	Email                []string `protobuf:"bytes,1,rep,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailConfirmationBadRequestV1) Reset()         { *m = CreateEmailConfirmationBadRequestV1{} }
func (m *CreateEmailConfirmationBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailConfirmationBadRequestV1) ProtoMessage()    {}
func (*CreateEmailConfirmationBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{14}
}
func (m *CreateEmailConfirmationBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailConfirmationBadRequestV1.Unmarshal(m, b)
}
func (m *CreateEmailConfirmationBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailConfirmationBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailConfirmationBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailConfirmationBadRequestV1.Merge(dst, src)
}
func (m *CreateEmailConfirmationBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailConfirmationBadRequestV1.Size(m)
}
func (m *CreateEmailConfirmationBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailConfirmationBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailConfirmationBadRequestV1 proto.InternalMessageInfo

func (m *CreateEmailConfirmationBadRequestV1) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

type CreateEmailConfirmationResponseV1 struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Expire               int64    `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailConfirmationResponseV1) Reset()         { *m = CreateEmailConfirmationResponseV1{} }
func (m *CreateEmailConfirmationResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailConfirmationResponseV1) ProtoMessage()    {}
func (*CreateEmailConfirmationResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{15}
}
func (m *CreateEmailConfirmationResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailConfirmationResponseV1.Unmarshal(m, b)
}
func (m *CreateEmailConfirmationResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailConfirmationResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailConfirmationResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailConfirmationResponseV1.Merge(dst, src)
}
func (m *CreateEmailConfirmationResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailConfirmationResponseV1.Size(m)
}
func (m *CreateEmailConfirmationResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailConfirmationResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailConfirmationResponseV1 proto.InternalMessageInfo

func (m *CreateEmailConfirmationResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CreateEmailConfirmationResponseV1) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *CreateEmailConfirmationResponseV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreatePhoneRequestV1 struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	UserID               []byte   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneRequestV1) Reset()         { *m = CreatePhoneRequestV1{} }
func (m *CreatePhoneRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneRequestV1) ProtoMessage()    {}
func (*CreatePhoneRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{16}
}
func (m *CreatePhoneRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneRequestV1.Unmarshal(m, b)
}
func (m *CreatePhoneRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneRequestV1.Merge(dst, src)
}
func (m *CreatePhoneRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneRequestV1.Size(m)
}
func (m *CreatePhoneRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneRequestV1 proto.InternalMessageInfo

func (m *CreatePhoneRequestV1) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreatePhoneRequestV1) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreatePhoneRequestV1) GetUserID() []byte {
	if m != nil {
		return m.UserID
	}
	return nil
}

type CreatePhoneBadRequestV1 struct {
	Phone                []string `protobuf:"bytes,1,rep,name=phone,proto3" json:"phone,omitempty"`
	Code                 []string `protobuf:"bytes,2,rep,name=code,proto3" json:"code,omitempty"`
	UserID               []string `protobuf:"bytes,3,rep,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneBadRequestV1) Reset()         { *m = CreatePhoneBadRequestV1{} }
func (m *CreatePhoneBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneBadRequestV1) ProtoMessage()    {}
func (*CreatePhoneBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{17}
}
func (m *CreatePhoneBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneBadRequestV1.Unmarshal(m, b)
}
func (m *CreatePhoneBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneBadRequestV1.Merge(dst, src)
}
func (m *CreatePhoneBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneBadRequestV1.Size(m)
}
func (m *CreatePhoneBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneBadRequestV1 proto.InternalMessageInfo

func (m *CreatePhoneBadRequestV1) GetPhone() []string {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *CreatePhoneBadRequestV1) GetCode() []string {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CreatePhoneBadRequestV1) GetUserID() []string {
	if m != nil {
		return m.UserID
	}
	return nil
}

type CreatePhoneResponseV1 struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	UserID               []byte   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneResponseV1) Reset()         { *m = CreatePhoneResponseV1{} }
func (m *CreatePhoneResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneResponseV1) ProtoMessage()    {}
func (*CreatePhoneResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{18}
}
func (m *CreatePhoneResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneResponseV1.Unmarshal(m, b)
}
func (m *CreatePhoneResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneResponseV1.Merge(dst, src)
}
func (m *CreatePhoneResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneResponseV1.Size(m)
}
func (m *CreatePhoneResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneResponseV1 proto.InternalMessageInfo

func (m *CreatePhoneResponseV1) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CreatePhoneResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CreatePhoneResponseV1) GetUserID() []byte {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *CreatePhoneResponseV1) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type CreatePhoneConfirmationRequestV1 struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneConfirmationRequestV1) Reset()         { *m = CreatePhoneConfirmationRequestV1{} }
func (m *CreatePhoneConfirmationRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneConfirmationRequestV1) ProtoMessage()    {}
func (*CreatePhoneConfirmationRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{19}
}
func (m *CreatePhoneConfirmationRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneConfirmationRequestV1.Unmarshal(m, b)
}
func (m *CreatePhoneConfirmationRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneConfirmationRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneConfirmationRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneConfirmationRequestV1.Merge(dst, src)
}
func (m *CreatePhoneConfirmationRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneConfirmationRequestV1.Size(m)
}
func (m *CreatePhoneConfirmationRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneConfirmationRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneConfirmationRequestV1 proto.InternalMessageInfo

func (m *CreatePhoneConfirmationRequestV1) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type CreatePhoneConfirmationBadRequestV1 struct {
	Phone                []string `protobuf:"bytes,1,rep,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneConfirmationBadRequestV1) Reset()         { *m = CreatePhoneConfirmationBadRequestV1{} }
func (m *CreatePhoneConfirmationBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneConfirmationBadRequestV1) ProtoMessage()    {}
func (*CreatePhoneConfirmationBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{20}
}
func (m *CreatePhoneConfirmationBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneConfirmationBadRequestV1.Unmarshal(m, b)
}
func (m *CreatePhoneConfirmationBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneConfirmationBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneConfirmationBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneConfirmationBadRequestV1.Merge(dst, src)
}
func (m *CreatePhoneConfirmationBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneConfirmationBadRequestV1.Size(m)
}
func (m *CreatePhoneConfirmationBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneConfirmationBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneConfirmationBadRequestV1 proto.InternalMessageInfo

func (m *CreatePhoneConfirmationBadRequestV1) GetPhone() []string {
	if m != nil {
		return m.Phone
	}
	return nil
}

type CreatePhoneConfirmationResponseV1 struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Expire               int64    `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneConfirmationResponseV1) Reset()         { *m = CreatePhoneConfirmationResponseV1{} }
func (m *CreatePhoneConfirmationResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneConfirmationResponseV1) ProtoMessage()    {}
func (*CreatePhoneConfirmationResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{21}
}
func (m *CreatePhoneConfirmationResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneConfirmationResponseV1.Unmarshal(m, b)
}
func (m *CreatePhoneConfirmationResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneConfirmationResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneConfirmationResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneConfirmationResponseV1.Merge(dst, src)
}
func (m *CreatePhoneConfirmationResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneConfirmationResponseV1.Size(m)
}
func (m *CreatePhoneConfirmationResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneConfirmationResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneConfirmationResponseV1 proto.InternalMessageInfo

func (m *CreatePhoneConfirmationResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CreatePhoneConfirmationResponseV1) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *CreatePhoneConfirmationResponseV1) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type CreatePasswordRequestV1 struct {
	UserID               []byte   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordRequestV1) Reset()         { *m = CreatePasswordRequestV1{} }
func (m *CreatePasswordRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordRequestV1) ProtoMessage()    {}
func (*CreatePasswordRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{22}
}
func (m *CreatePasswordRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordRequestV1.Unmarshal(m, b)
}
func (m *CreatePasswordRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreatePasswordRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordRequestV1.Merge(dst, src)
}
func (m *CreatePasswordRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordRequestV1.Size(m)
}
func (m *CreatePasswordRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordRequestV1 proto.InternalMessageInfo

func (m *CreatePasswordRequestV1) GetUserID() []byte {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *CreatePasswordRequestV1) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CreatePasswordBadRequestResponseV1 struct {
	UserID               []string `protobuf:"bytes,1,rep,name=userID,proto3" json:"userID,omitempty"`
	Value                []string `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordBadRequestResponseV1) Reset()         { *m = CreatePasswordBadRequestResponseV1{} }
func (m *CreatePasswordBadRequestResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordBadRequestResponseV1) ProtoMessage()    {}
func (*CreatePasswordBadRequestResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{23}
}
func (m *CreatePasswordBadRequestResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordBadRequestResponseV1.Unmarshal(m, b)
}
func (m *CreatePasswordBadRequestResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordBadRequestResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreatePasswordBadRequestResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordBadRequestResponseV1.Merge(dst, src)
}
func (m *CreatePasswordBadRequestResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordBadRequestResponseV1.Size(m)
}
func (m *CreatePasswordBadRequestResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordBadRequestResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordBadRequestResponseV1 proto.InternalMessageInfo

func (m *CreatePasswordBadRequestResponseV1) GetUserID() []string {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *CreatePasswordBadRequestResponseV1) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type CreatePasswordResponseV1 struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	UserID               []byte   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordResponseV1) Reset()         { *m = CreatePasswordResponseV1{} }
func (m *CreatePasswordResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordResponseV1) ProtoMessage()    {}
func (*CreatePasswordResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{24}
}
func (m *CreatePasswordResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordResponseV1.Unmarshal(m, b)
}
func (m *CreatePasswordResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreatePasswordResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordResponseV1.Merge(dst, src)
}
func (m *CreatePasswordResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordResponseV1.Size(m)
}
func (m *CreatePasswordResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordResponseV1 proto.InternalMessageInfo

func (m *CreatePasswordResponseV1) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CreatePasswordResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CreatePasswordResponseV1) GetUserID() []byte {
	if m != nil {
		return m.UserID
	}
	return nil
}

type CreateUserRequestV1 struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneCode            string   `protobuf:"bytes,4,opt,name=phoneCode,proto3" json:"phoneCode,omitempty"`
	EmailCode            string   `protobuf:"bytes,5,opt,name=emailCode,proto3" json:"emailCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequestV1) Reset()         { *m = CreateUserRequestV1{} }
func (m *CreateUserRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequestV1) ProtoMessage()    {}
func (*CreateUserRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{25}
}
func (m *CreateUserRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequestV1.Unmarshal(m, b)
}
func (m *CreateUserRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequestV1.Merge(dst, src)
}
func (m *CreateUserRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequestV1.Size(m)
}
func (m *CreateUserRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequestV1 proto.InternalMessageInfo

func (m *CreateUserRequestV1) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequestV1) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateUserRequestV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequestV1) GetPhoneCode() string {
	if m != nil {
		return m.PhoneCode
	}
	return ""
}

func (m *CreateUserRequestV1) GetEmailCode() string {
	if m != nil {
		return m.EmailCode
	}
	return ""
}

type CreateUserBadRequestV1 struct {
	Password             []string `protobuf:"bytes,1,rep,name=password,proto3" json:"password,omitempty"`
	Phone                []string `protobuf:"bytes,2,rep,name=phone,proto3" json:"phone,omitempty"`
	Email                []string `protobuf:"bytes,3,rep,name=email,proto3" json:"email,omitempty"`
	PhoneCode            []string `protobuf:"bytes,4,rep,name=phoneCode,proto3" json:"phoneCode,omitempty"`
	EmailCode            []string `protobuf:"bytes,5,rep,name=emailCode,proto3" json:"emailCode,omitempty"`
	Errors               []string `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserBadRequestV1) Reset()         { *m = CreateUserBadRequestV1{} }
func (m *CreateUserBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserBadRequestV1) ProtoMessage()    {}
func (*CreateUserBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{26}
}
func (m *CreateUserBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserBadRequestV1.Unmarshal(m, b)
}
func (m *CreateUserBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserBadRequestV1.Merge(dst, src)
}
func (m *CreateUserBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserBadRequestV1.Size(m)
}
func (m *CreateUserBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserBadRequestV1 proto.InternalMessageInfo

func (m *CreateUserBadRequestV1) GetPassword() []string {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *CreateUserBadRequestV1) GetPhone() []string {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *CreateUserBadRequestV1) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *CreateUserBadRequestV1) GetPhoneCode() []string {
	if m != nil {
		return m.PhoneCode
	}
	return nil
}

func (m *CreateUserBadRequestV1) GetEmailCode() []string {
	if m != nil {
		return m.EmailCode
	}
	return nil
}

func (m *CreateUserBadRequestV1) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type GetUserResponseV1 struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponseV1) Reset()         { *m = GetUserResponseV1{} }
func (m *GetUserResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetUserResponseV1) ProtoMessage()    {}
func (*GetUserResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{27}
}
func (m *GetUserResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponseV1.Unmarshal(m, b)
}
func (m *GetUserResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponseV1.Marshal(b, m, deterministic)
}
func (dst *GetUserResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponseV1.Merge(dst, src)
}
func (m *GetUserResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetUserResponseV1.Size(m)
}
func (m *GetUserResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponseV1 proto.InternalMessageInfo

func (m *GetUserResponseV1) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetUserResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type ListUserResponseV1 struct {
	Data                 []*GetUserResponseV1 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListUserResponseV1) Reset()         { *m = ListUserResponseV1{} }
func (m *ListUserResponseV1) String() string { return proto.CompactTextString(m) }
func (*ListUserResponseV1) ProtoMessage()    {}
func (*ListUserResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{28}
}
func (m *ListUserResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResponseV1.Unmarshal(m, b)
}
func (m *ListUserResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResponseV1.Marshal(b, m, deterministic)
}
func (dst *ListUserResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResponseV1.Merge(dst, src)
}
func (m *ListUserResponseV1) XXX_Size() int {
	return xxx_messageInfo_ListUserResponseV1.Size(m)
}
func (m *ListUserResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResponseV1 proto.InternalMessageInfo

func (m *ListUserResponseV1) GetData() []*GetUserResponseV1 {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateSessionRequestV1 struct {
	Fingerprint string `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	UserAgent   string `protobuf:"bytes,2,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*CreateSessionRequestV1_PhoneAndPassword_
	//	*CreateSessionRequestV1_PhoneAndCode_
	//	*CreateSessionRequestV1_EmailAndPassword_
	//	*CreateSessionRequestV1_EmailAndCode_
	//	*CreateSessionRequestV1_Tokens_
	Data                 isCreateSessionRequestV1_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CreateSessionRequestV1) Reset()         { *m = CreateSessionRequestV1{} }
func (m *CreateSessionRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequestV1) ProtoMessage()    {}
func (*CreateSessionRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{29}
}
func (m *CreateSessionRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequestV1.Unmarshal(m, b)
}
func (m *CreateSessionRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateSessionRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequestV1.Merge(dst, src)
}
func (m *CreateSessionRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequestV1.Size(m)
}
func (m *CreateSessionRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequestV1 proto.InternalMessageInfo

func (m *CreateSessionRequestV1) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *CreateSessionRequestV1) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

type isCreateSessionRequestV1_Data interface {
	isCreateSessionRequestV1_Data()
}

type CreateSessionRequestV1_PhoneAndPassword_ struct {
	PhoneAndPassword *CreateSessionRequestV1_PhoneAndPassword `protobuf:"bytes,3,opt,name=phoneAndPassword,proto3,oneof"`
}

type CreateSessionRequestV1_PhoneAndCode_ struct {
	PhoneAndCode *CreateSessionRequestV1_PhoneAndCode `protobuf:"bytes,4,opt,name=phoneAndCode,proto3,oneof"`
}

type CreateSessionRequestV1_EmailAndPassword_ struct {
	EmailAndPassword *CreateSessionRequestV1_EmailAndPassword `protobuf:"bytes,5,opt,name=emailAndPassword,proto3,oneof"`
}

type CreateSessionRequestV1_EmailAndCode_ struct {
	EmailAndCode *CreateSessionRequestV1_EmailAndCode `protobuf:"bytes,6,opt,name=emailAndCode,proto3,oneof"`
}

type CreateSessionRequestV1_Tokens_ struct {
	Tokens *CreateSessionRequestV1_Tokens `protobuf:"bytes,7,opt,name=tokens,proto3,oneof"`
}

func (*CreateSessionRequestV1_PhoneAndPassword_) isCreateSessionRequestV1_Data() {}

func (*CreateSessionRequestV1_PhoneAndCode_) isCreateSessionRequestV1_Data() {}

func (*CreateSessionRequestV1_EmailAndPassword_) isCreateSessionRequestV1_Data() {}

func (*CreateSessionRequestV1_EmailAndCode_) isCreateSessionRequestV1_Data() {}

func (*CreateSessionRequestV1_Tokens_) isCreateSessionRequestV1_Data() {}

func (m *CreateSessionRequestV1) GetData() isCreateSessionRequestV1_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateSessionRequestV1) GetPhoneAndPassword() *CreateSessionRequestV1_PhoneAndPassword {
	if x, ok := m.GetData().(*CreateSessionRequestV1_PhoneAndPassword_); ok {
		return x.PhoneAndPassword
	}
	return nil
}

func (m *CreateSessionRequestV1) GetPhoneAndCode() *CreateSessionRequestV1_PhoneAndCode {
	if x, ok := m.GetData().(*CreateSessionRequestV1_PhoneAndCode_); ok {
		return x.PhoneAndCode
	}
	return nil
}

func (m *CreateSessionRequestV1) GetEmailAndPassword() *CreateSessionRequestV1_EmailAndPassword {
	if x, ok := m.GetData().(*CreateSessionRequestV1_EmailAndPassword_); ok {
		return x.EmailAndPassword
	}
	return nil
}

func (m *CreateSessionRequestV1) GetEmailAndCode() *CreateSessionRequestV1_EmailAndCode {
	if x, ok := m.GetData().(*CreateSessionRequestV1_EmailAndCode_); ok {
		return x.EmailAndCode
	}
	return nil
}

func (m *CreateSessionRequestV1) GetTokens() *CreateSessionRequestV1_Tokens {
	if x, ok := m.GetData().(*CreateSessionRequestV1_Tokens_); ok {
		return x.Tokens
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CreateSessionRequestV1) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CreateSessionRequestV1_OneofMarshaler, _CreateSessionRequestV1_OneofUnmarshaler, _CreateSessionRequestV1_OneofSizer, []interface{}{
		(*CreateSessionRequestV1_PhoneAndPassword_)(nil),
		(*CreateSessionRequestV1_PhoneAndCode_)(nil),
		(*CreateSessionRequestV1_EmailAndPassword_)(nil),
		(*CreateSessionRequestV1_EmailAndCode_)(nil),
		(*CreateSessionRequestV1_Tokens_)(nil),
	}
}

func _CreateSessionRequestV1_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CreateSessionRequestV1)
	// data
	switch x := m.Data.(type) {
	case *CreateSessionRequestV1_PhoneAndPassword_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PhoneAndPassword); err != nil {
			return err
		}
	case *CreateSessionRequestV1_PhoneAndCode_:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PhoneAndCode); err != nil {
			return err
		}
	case *CreateSessionRequestV1_EmailAndPassword_:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EmailAndPassword); err != nil {
			return err
		}
	case *CreateSessionRequestV1_EmailAndCode_:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EmailAndCode); err != nil {
			return err
		}
	case *CreateSessionRequestV1_Tokens_:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Tokens); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CreateSessionRequestV1.Data has unexpected type %T", x)
	}
	return nil
}

func _CreateSessionRequestV1_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CreateSessionRequestV1)
	switch tag {
	case 3: // data.phoneAndPassword
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateSessionRequestV1_PhoneAndPassword)
		err := b.DecodeMessage(msg)
		m.Data = &CreateSessionRequestV1_PhoneAndPassword_{msg}
		return true, err
	case 4: // data.phoneAndCode
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateSessionRequestV1_PhoneAndCode)
		err := b.DecodeMessage(msg)
		m.Data = &CreateSessionRequestV1_PhoneAndCode_{msg}
		return true, err
	case 5: // data.emailAndPassword
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateSessionRequestV1_EmailAndPassword)
		err := b.DecodeMessage(msg)
		m.Data = &CreateSessionRequestV1_EmailAndPassword_{msg}
		return true, err
	case 6: // data.emailAndCode
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateSessionRequestV1_EmailAndCode)
		err := b.DecodeMessage(msg)
		m.Data = &CreateSessionRequestV1_EmailAndCode_{msg}
		return true, err
	case 7: // data.tokens
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateSessionRequestV1_Tokens)
		err := b.DecodeMessage(msg)
		m.Data = &CreateSessionRequestV1_Tokens_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CreateSessionRequestV1_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CreateSessionRequestV1)
	// data
	switch x := m.Data.(type) {
	case *CreateSessionRequestV1_PhoneAndPassword_:
		s := proto.Size(x.PhoneAndPassword)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CreateSessionRequestV1_PhoneAndCode_:
		s := proto.Size(x.PhoneAndCode)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CreateSessionRequestV1_EmailAndPassword_:
		s := proto.Size(x.EmailAndPassword)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CreateSessionRequestV1_EmailAndCode_:
		s := proto.Size(x.EmailAndCode)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CreateSessionRequestV1_Tokens_:
		s := proto.Size(x.Tokens)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateSessionRequestV1_PhoneAndPassword struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionRequestV1_PhoneAndPassword) Reset() {
	*m = CreateSessionRequestV1_PhoneAndPassword{}
}
func (m *CreateSessionRequestV1_PhoneAndPassword) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequestV1_PhoneAndPassword) ProtoMessage()    {}
func (*CreateSessionRequestV1_PhoneAndPassword) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{29, 0}
}
func (m *CreateSessionRequestV1_PhoneAndPassword) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequestV1_PhoneAndPassword.Unmarshal(m, b)
}
func (m *CreateSessionRequestV1_PhoneAndPassword) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequestV1_PhoneAndPassword.Marshal(b, m, deterministic)
}
func (dst *CreateSessionRequestV1_PhoneAndPassword) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequestV1_PhoneAndPassword.Merge(dst, src)
}
func (m *CreateSessionRequestV1_PhoneAndPassword) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequestV1_PhoneAndPassword.Size(m)
}
func (m *CreateSessionRequestV1_PhoneAndPassword) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequestV1_PhoneAndPassword.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequestV1_PhoneAndPassword proto.InternalMessageInfo

func (m *CreateSessionRequestV1_PhoneAndPassword) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateSessionRequestV1_PhoneAndPassword) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateSessionRequestV1_PhoneAndCode struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionRequestV1_PhoneAndCode) Reset()         { *m = CreateSessionRequestV1_PhoneAndCode{} }
func (m *CreateSessionRequestV1_PhoneAndCode) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequestV1_PhoneAndCode) ProtoMessage()    {}
func (*CreateSessionRequestV1_PhoneAndCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{29, 1}
}
func (m *CreateSessionRequestV1_PhoneAndCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequestV1_PhoneAndCode.Unmarshal(m, b)
}
func (m *CreateSessionRequestV1_PhoneAndCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequestV1_PhoneAndCode.Marshal(b, m, deterministic)
}
func (dst *CreateSessionRequestV1_PhoneAndCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequestV1_PhoneAndCode.Merge(dst, src)
}
func (m *CreateSessionRequestV1_PhoneAndCode) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequestV1_PhoneAndCode.Size(m)
}
func (m *CreateSessionRequestV1_PhoneAndCode) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequestV1_PhoneAndCode.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequestV1_PhoneAndCode proto.InternalMessageInfo

func (m *CreateSessionRequestV1_PhoneAndCode) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateSessionRequestV1_PhoneAndCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type CreateSessionRequestV1_EmailAndPassword struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionRequestV1_EmailAndPassword) Reset() {
	*m = CreateSessionRequestV1_EmailAndPassword{}
}
func (m *CreateSessionRequestV1_EmailAndPassword) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequestV1_EmailAndPassword) ProtoMessage()    {}
func (*CreateSessionRequestV1_EmailAndPassword) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{29, 2}
}
func (m *CreateSessionRequestV1_EmailAndPassword) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequestV1_EmailAndPassword.Unmarshal(m, b)
}
func (m *CreateSessionRequestV1_EmailAndPassword) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequestV1_EmailAndPassword.Marshal(b, m, deterministic)
}
func (dst *CreateSessionRequestV1_EmailAndPassword) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequestV1_EmailAndPassword.Merge(dst, src)
}
func (m *CreateSessionRequestV1_EmailAndPassword) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequestV1_EmailAndPassword.Size(m)
}
func (m *CreateSessionRequestV1_EmailAndPassword) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequestV1_EmailAndPassword.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequestV1_EmailAndPassword proto.InternalMessageInfo

func (m *CreateSessionRequestV1_EmailAndPassword) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateSessionRequestV1_EmailAndPassword) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateSessionRequestV1_EmailAndCode struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionRequestV1_EmailAndCode) Reset()         { *m = CreateSessionRequestV1_EmailAndCode{} }
func (m *CreateSessionRequestV1_EmailAndCode) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequestV1_EmailAndCode) ProtoMessage()    {}
func (*CreateSessionRequestV1_EmailAndCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{29, 3}
}
func (m *CreateSessionRequestV1_EmailAndCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequestV1_EmailAndCode.Unmarshal(m, b)
}
func (m *CreateSessionRequestV1_EmailAndCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequestV1_EmailAndCode.Marshal(b, m, deterministic)
}
func (dst *CreateSessionRequestV1_EmailAndCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequestV1_EmailAndCode.Merge(dst, src)
}
func (m *CreateSessionRequestV1_EmailAndCode) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequestV1_EmailAndCode.Size(m)
}
func (m *CreateSessionRequestV1_EmailAndCode) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequestV1_EmailAndCode.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequestV1_EmailAndCode proto.InternalMessageInfo

func (m *CreateSessionRequestV1_EmailAndCode) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateSessionRequestV1_EmailAndCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type CreateSessionRequestV1_Tokens struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionRequestV1_Tokens) Reset()         { *m = CreateSessionRequestV1_Tokens{} }
func (m *CreateSessionRequestV1_Tokens) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequestV1_Tokens) ProtoMessage()    {}
func (*CreateSessionRequestV1_Tokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{29, 4}
}
func (m *CreateSessionRequestV1_Tokens) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequestV1_Tokens.Unmarshal(m, b)
}
func (m *CreateSessionRequestV1_Tokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequestV1_Tokens.Marshal(b, m, deterministic)
}
func (dst *CreateSessionRequestV1_Tokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequestV1_Tokens.Merge(dst, src)
}
func (m *CreateSessionRequestV1_Tokens) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequestV1_Tokens.Size(m)
}
func (m *CreateSessionRequestV1_Tokens) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequestV1_Tokens.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequestV1_Tokens proto.InternalMessageInfo

func (m *CreateSessionRequestV1_Tokens) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreateSessionRequestV1_Tokens) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type CreateSessionBadRequestResponseV1 struct {
	Email                []string `protobuf:"bytes,1,rep,name=email,proto3" json:"email,omitempty"`
	EmailCode            []string `protobuf:"bytes,2,rep,name=emailCode,proto3" json:"emailCode,omitempty"`
	Phone                []string `protobuf:"bytes,3,rep,name=phone,proto3" json:"phone,omitempty"`
	PhoneCode            []string `protobuf:"bytes,4,rep,name=phoneCode,proto3" json:"phoneCode,omitempty"`
	Password             []string `protobuf:"bytes,5,rep,name=password,proto3" json:"password,omitempty"`
	Fingerprint          []string `protobuf:"bytes,6,rep,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	UserAgent            []string `protobuf:"bytes,7,rep,name=userAgent,proto3" json:"userAgent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionBadRequestResponseV1) Reset()         { *m = CreateSessionBadRequestResponseV1{} }
func (m *CreateSessionBadRequestResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreateSessionBadRequestResponseV1) ProtoMessage()    {}
func (*CreateSessionBadRequestResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{30}
}
func (m *CreateSessionBadRequestResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionBadRequestResponseV1.Unmarshal(m, b)
}
func (m *CreateSessionBadRequestResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionBadRequestResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreateSessionBadRequestResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionBadRequestResponseV1.Merge(dst, src)
}
func (m *CreateSessionBadRequestResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreateSessionBadRequestResponseV1.Size(m)
}
func (m *CreateSessionBadRequestResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionBadRequestResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionBadRequestResponseV1 proto.InternalMessageInfo

func (m *CreateSessionBadRequestResponseV1) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *CreateSessionBadRequestResponseV1) GetEmailCode() []string {
	if m != nil {
		return m.EmailCode
	}
	return nil
}

func (m *CreateSessionBadRequestResponseV1) GetPhone() []string {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *CreateSessionBadRequestResponseV1) GetPhoneCode() []string {
	if m != nil {
		return m.PhoneCode
	}
	return nil
}

func (m *CreateSessionBadRequestResponseV1) GetPassword() []string {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *CreateSessionBadRequestResponseV1) GetFingerprint() []string {
	if m != nil {
		return m.Fingerprint
	}
	return nil
}

func (m *CreateSessionBadRequestResponseV1) GetUserAgent() []string {
	if m != nil {
		return m.UserAgent
	}
	return nil
}

type CreateSessionResponseV1 struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionResponseV1) Reset()         { *m = CreateSessionResponseV1{} }
func (m *CreateSessionResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreateSessionResponseV1) ProtoMessage()    {}
func (*CreateSessionResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{31}
}
func (m *CreateSessionResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionResponseV1.Unmarshal(m, b)
}
func (m *CreateSessionResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreateSessionResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionResponseV1.Merge(dst, src)
}
func (m *CreateSessionResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreateSessionResponseV1.Size(m)
}
func (m *CreateSessionResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionResponseV1 proto.InternalMessageInfo

func (m *CreateSessionResponseV1) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *CreateSessionResponseV1) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type GetSecretResponseV1 struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSecretResponseV1) Reset()         { *m = GetSecretResponseV1{} }
func (m *GetSecretResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetSecretResponseV1) ProtoMessage()    {}
func (*GetSecretResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{32}
}
func (m *GetSecretResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSecretResponseV1.Unmarshal(m, b)
}
func (m *GetSecretResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSecretResponseV1.Marshal(b, m, deterministic)
}
func (dst *GetSecretResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSecretResponseV1.Merge(dst, src)
}
func (m *GetSecretResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetSecretResponseV1.Size(m)
}
func (m *GetSecretResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSecretResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetSecretResponseV1 proto.InternalMessageInfo

func (m *GetSecretResponseV1) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetSecretResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *GetSecretResponseV1) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetUserViewResponseV1 struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Roles                []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Phones               []string `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	Emails               []string `protobuf:"bytes,5,rep,name=emails,proto3" json:"emails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserViewResponseV1) Reset()         { *m = GetUserViewResponseV1{} }
func (m *GetUserViewResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetUserViewResponseV1) ProtoMessage()    {}
func (*GetUserViewResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{33}
}
func (m *GetUserViewResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserViewResponseV1.Unmarshal(m, b)
}
func (m *GetUserViewResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserViewResponseV1.Marshal(b, m, deterministic)
}
func (dst *GetUserViewResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserViewResponseV1.Merge(dst, src)
}
func (m *GetUserViewResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetUserViewResponseV1.Size(m)
}
func (m *GetUserViewResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserViewResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserViewResponseV1 proto.InternalMessageInfo

func (m *GetUserViewResponseV1) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetUserViewResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *GetUserViewResponseV1) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *GetUserViewResponseV1) GetPhones() []string {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *GetUserViewResponseV1) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

type ListUserViewResponseV1 struct {
	Data                 []*GetUserViewResponseV1 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ListUserViewResponseV1) Reset()         { *m = ListUserViewResponseV1{} }
func (m *ListUserViewResponseV1) String() string { return proto.CompactTextString(m) }
func (*ListUserViewResponseV1) ProtoMessage()    {}
func (*ListUserViewResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4df01167f0265bd8, []int{34}
}
func (m *ListUserViewResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserViewResponseV1.Unmarshal(m, b)
}
func (m *ListUserViewResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserViewResponseV1.Marshal(b, m, deterministic)
}
func (dst *ListUserViewResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserViewResponseV1.Merge(dst, src)
}
func (m *ListUserViewResponseV1) XXX_Size() int {
	return xxx_messageInfo_ListUserViewResponseV1.Size(m)
}
func (m *ListUserViewResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserViewResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserViewResponseV1 proto.InternalMessageInfo

func (m *ListUserViewResponseV1) GetData() []*GetUserViewResponseV1 {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRoleRequestV1)(nil), "inout.CreateRoleRequestV1")
	proto.RegisterType((*CreateRoleBadRequestV1)(nil), "inout.CreateRoleBadRequestV1")
	proto.RegisterType((*GetRoleResponseV1)(nil), "inout.GetRoleResponseV1")
	proto.RegisterType((*ListRoleResponseV1)(nil), "inout.ListRoleResponseV1")
	proto.RegisterType((*CreateUserRoleRequestV1)(nil), "inout.CreateUserRoleRequestV1")
	proto.RegisterType((*CreateUserRoleBadRequestV1)(nil), "inout.CreateUserRoleBadRequestV1")
	proto.RegisterType((*CreateUserRolesRequestV1)(nil), "inout.CreateUserRolesRequestV1")
	proto.RegisterType((*CreateUserRolesBadRequestV1)(nil), "inout.CreateUserRolesBadRequestV1")
	proto.RegisterType((*GetUserRoleResponseV1)(nil), "inout.GetUserRoleResponseV1")
	proto.RegisterType((*ListUserRolesResponseV1)(nil), "inout.ListUserRolesResponseV1")
	proto.RegisterType((*CreateEmailRequestV1)(nil), "inout.CreateEmailRequestV1")
	proto.RegisterType((*CreateEmailBadRequestV1)(nil), "inout.CreateEmailBadRequestV1")
	proto.RegisterType((*CreateEmailResponseV1)(nil), "inout.CreateEmailResponseV1")
	proto.RegisterType((*CreateEmailConfirmationRequestV1)(nil), "inout.CreateEmailConfirmationRequestV1")
	proto.RegisterType((*CreateEmailConfirmationBadRequestV1)(nil), "inout.CreateEmailConfirmationBadRequestV1")
	proto.RegisterType((*CreateEmailConfirmationResponseV1)(nil), "inout.CreateEmailConfirmationResponseV1")
	proto.RegisterType((*CreatePhoneRequestV1)(nil), "inout.CreatePhoneRequestV1")
	proto.RegisterType((*CreatePhoneBadRequestV1)(nil), "inout.CreatePhoneBadRequestV1")
	proto.RegisterType((*CreatePhoneResponseV1)(nil), "inout.CreatePhoneResponseV1")
	proto.RegisterType((*CreatePhoneConfirmationRequestV1)(nil), "inout.CreatePhoneConfirmationRequestV1")
	proto.RegisterType((*CreatePhoneConfirmationBadRequestV1)(nil), "inout.CreatePhoneConfirmationBadRequestV1")
	proto.RegisterType((*CreatePhoneConfirmationResponseV1)(nil), "inout.CreatePhoneConfirmationResponseV1")
	proto.RegisterType((*CreatePasswordRequestV1)(nil), "inout.CreatePasswordRequestV1")
	proto.RegisterType((*CreatePasswordBadRequestResponseV1)(nil), "inout.CreatePasswordBadRequestResponseV1")
	proto.RegisterType((*CreatePasswordResponseV1)(nil), "inout.CreatePasswordResponseV1")
	proto.RegisterType((*CreateUserRequestV1)(nil), "inout.CreateUserRequestV1")
	proto.RegisterType((*CreateUserBadRequestV1)(nil), "inout.CreateUserBadRequestV1")
	proto.RegisterType((*GetUserResponseV1)(nil), "inout.GetUserResponseV1")
	proto.RegisterType((*ListUserResponseV1)(nil), "inout.ListUserResponseV1")
	proto.RegisterType((*CreateSessionRequestV1)(nil), "inout.CreateSessionRequestV1")
	proto.RegisterType((*CreateSessionRequestV1_PhoneAndPassword)(nil), "inout.CreateSessionRequestV1.PhoneAndPassword")
	proto.RegisterType((*CreateSessionRequestV1_PhoneAndCode)(nil), "inout.CreateSessionRequestV1.PhoneAndCode")
	proto.RegisterType((*CreateSessionRequestV1_EmailAndPassword)(nil), "inout.CreateSessionRequestV1.EmailAndPassword")
	proto.RegisterType((*CreateSessionRequestV1_EmailAndCode)(nil), "inout.CreateSessionRequestV1.EmailAndCode")
	proto.RegisterType((*CreateSessionRequestV1_Tokens)(nil), "inout.CreateSessionRequestV1.Tokens")
	proto.RegisterType((*CreateSessionBadRequestResponseV1)(nil), "inout.CreateSessionBadRequestResponseV1")
	proto.RegisterType((*CreateSessionResponseV1)(nil), "inout.CreateSessionResponseV1")
	proto.RegisterType((*GetSecretResponseV1)(nil), "inout.GetSecretResponseV1")
	proto.RegisterType((*GetUserViewResponseV1)(nil), "inout.GetUserViewResponseV1")
	proto.RegisterType((*ListUserViewResponseV1)(nil), "inout.ListUserViewResponseV1")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_4df01167f0265bd8) }

var fileDescriptor_api_4df01167f0265bd8 = []byte{
	// 1027 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xef, 0x6e, 0xdc, 0x44,
	0x10, 0x8f, 0x6f, 0xef, 0x1c, 0x6e, 0x72, 0x42, 0xc5, 0x4d, 0x53, 0xeb, 0xa8, 0x50, 0xba, 0xf0,
	0xa1, 0x02, 0x74, 0xa2, 0xe1, 0x4b, 0x11, 0x2a, 0x52, 0xd3, 0x44, 0x49, 0x00, 0xa1, 0xc8, 0xa1,
	0x51, 0x11, 0x95, 0x2a, 0x73, 0xde, 0xb4, 0x56, 0xaf, 0xb6, 0xbb, 0xeb, 0x23, 0xbc, 0x01, 0xcf,
	0xc0, 0x7b, 0xf0, 0x20, 0xbc, 0x05, 0xaf, 0x81, 0xf6, 0x9f, 0xf7, 0x8f, 0xed, 0xdc, 0x91, 0xe6,
	0xdb, 0xcd, 0xdc, 0xee, 0x6f, 0x7e, 0x33, 0xf3, 0xdb, 0x9d, 0x35, 0x8c, 0xd3, 0x2a, 0x9f, 0x55,
	0xb4, 0xac, 0xcb, 0x68, 0x94, 0x17, 0xe5, 0xb2, 0xc6, 0x5f, 0xc0, 0xed, 0xa7, 0x94, 0xa4, 0x35,
	0x49, 0xca, 0x05, 0x49, 0xc8, 0xbb, 0x25, 0x61, 0xf5, 0xf9, 0xc3, 0x68, 0x1b, 0x46, 0x75, 0x5e,
	0x2f, 0x48, 0x1c, 0xec, 0x06, 0x0f, 0xc6, 0x89, 0x34, 0xf0, 0x0c, 0x76, 0xcc, 0xe2, 0xfd, 0x34,
	0xeb, 0x5c, 0x8f, 0xcc, 0xfa, 0x33, 0xf8, 0xe8, 0x88, 0xd4, 0x12, 0x99, 0x55, 0x65, 0xc1, 0xc8,
	0xf9, 0xc3, 0xe8, 0x43, 0x18, 0xe4, 0x99, 0xc0, 0x9d, 0x24, 0x83, 0x3c, 0x8b, 0x62, 0xd8, 0x9c,
	0x0b, 0xd0, 0x2c, 0x1e, 0xec, 0x06, 0x0f, 0x50, 0xa2, 0x4d, 0x03, 0x8a, 0x6c, 0x12, 0xfb, 0x10,
	0xfd, 0x98, 0x33, 0x1f, 0xf5, 0x4b, 0x18, 0x66, 0x69, 0x9d, 0x8a, 0xf8, 0x5b, 0x7b, 0xf1, 0x4c,
	0x64, 0x37, 0x6b, 0x45, 0x4f, 0xc4, 0x2a, 0x7c, 0x02, 0x77, 0x65, 0x22, 0xcf, 0x18, 0xa1, 0x6e,
	0xe6, 0x3b, 0x10, 0x2e, 0x19, 0xa1, 0x27, 0x07, 0x8a, 0xa2, 0xb2, 0xb8, 0x9f, 0x96, 0x0b, 0x72,
	0x72, 0x20, 0x58, 0x4e, 0x12, 0x65, 0xe1, 0x0c, 0xa6, 0x2e, 0x94, 0x53, 0x17, 0x1b, 0x8d, 0x17,
	0xa6, 0x0b, 0x4d, 0xf8, 0xa5, 0xc5, 0xfd, 0x84, 0xd2, 0x92, 0xb2, 0x18, 0x49, 0xbf, 0xb4, 0xf0,
	0x2f, 0x10, 0xbb, 0x51, 0x98, 0x89, 0xf1, 0x18, 0x80, 0xa3, 0xbe, 0xe4, 0x10, 0x4c, 0x15, 0xe0,
	0x13, 0x55, 0x80, 0x9e, 0x2c, 0x93, 0xf1, 0x52, 0xe3, 0xe0, 0xe7, 0xf0, 0xb1, 0x07, 0xed, 0x64,
	0xf0, 0x4d, 0xc3, 0x48, 0x22, 0xdf, 0xef, 0x44, 0xb6, 0xb7, 0x34, 0xa4, 0xdf, 0xc1, 0x9d, 0x23,
	0x52, 0x9b, 0xe0, 0xd7, 0x90, 0x80, 0xa9, 0x1f, 0xea, 0xe9, 0xc6, 0xd0, 0xe9, 0xc6, 0x0f, 0x70,
	0x97, 0x8b, 0xc3, 0xaa, 0x52, 0x13, 0xf4, 0x2b, 0x47, 0x21, 0xf7, 0x8c, 0x42, 0xda, 0x04, 0x95,
	0x4a, 0x9e, 0xc3, 0xb6, 0xcc, 0xf2, 0xf0, 0x6d, 0x9a, 0x2f, 0x1c, 0xb1, 0x13, 0xee, 0xd1, 0x87,
	0x43, 0x18, 0x51, 0x04, 0xc3, 0x79, 0x99, 0x11, 0x91, 0xc1, 0x38, 0x11, 0xbf, 0xfb, 0xe8, 0xe3,
	0x5f, 0xb5, 0xfe, 0x04, 0xb2, 0x7f, 0x92, 0x34, 0x38, 0xea, 0x02, 0x47, 0x2d, 0xf0, 0x4c, 0x6b,
	0x45, 0x5a, 0xb8, 0x84, 0x3b, 0x0e, 0xed, 0x1b, 0x2c, 0x7b, 0x43, 0x6e, 0x68, 0x65, 0x8e, 0x1f,
	0xc1, 0xae, 0x15, 0xf0, 0x69, 0x59, 0x5c, 0xe4, 0xf4, 0x6d, 0x5a, 0xe7, 0x65, 0xb1, 0xa2, 0x66,
	0xf8, 0x5b, 0xf8, 0xb4, 0x67, 0xe7, 0xea, 0x9a, 0xe0, 0x37, 0x70, 0xbf, 0x37, 0x6c, 0x93, 0xb3,
	0x95, 0x63, 0xd0, 0xca, 0x91, 0xfc, 0x51, 0xe5, 0x94, 0xa8, 0xe4, 0x95, 0x65, 0x82, 0x21, 0x9b,
	0x69, 0xa3, 0x85, 0xd3, 0xd7, 0x65, 0xe1, 0x5e, 0x94, 0x15, 0xf7, 0xe8, 0xbc, 0x84, 0x71, 0x3d,
	0x2d, 0x08, 0x64, 0x3f, 0x6f, 0x0d, 0x8e, 0xba, 0xc0, 0x51, 0x27, 0xb8, 0x75, 0xcf, 0x18, 0x2d,
	0x28, 0xda, 0x37, 0xab, 0x05, 0x49, 0x6e, 0x68, 0x65, 0x6e, 0xb4, 0x20, 0x02, 0xf6, 0x6a, 0xa1,
	0x5d, 0x33, 0xa3, 0x85, 0xd6, 0xce, 0xd5, 0x35, 0x31, 0x5a, 0xe8, 0x08, 0xfb, 0x7e, 0x5a, 0x90,
	0xc1, 0x90, 0xcd, 0xf4, 0xa8, 0xe9, 0x58, 0xca, 0xd8, 0x65, 0x49, 0xb3, 0xd5, 0xd3, 0x63, 0x1b,
	0x46, 0xbf, 0xa7, 0x8b, 0xa5, 0x56, 0x84, 0x34, 0x70, 0x02, 0xd8, 0x05, 0x32, 0x99, 0x5a, 0xb4,
	0xfb, 0x66, 0x88, 0x85, 0x89, 0x0c, 0xe6, 0x0b, 0x3d, 0x29, 0x0c, 0xb9, 0x9b, 0x6b, 0x3a, 0xfe,
	0x2b, 0xd0, 0xef, 0x05, 0x71, 0x6b, 0x36, 0x79, 0x4f, 0xe1, 0x83, 0x4a, 0xc5, 0x53, 0x5d, 0x6d,
	0x6c, 0x53, 0xc4, 0x81, 0x7d, 0x44, 0x3a, 0x8f, 0x59, 0x74, 0x0f, 0xc6, 0x95, 0xec, 0x60, 0xa6,
	0x85, 0x65, 0x1c, 0xfc, 0x5f, 0x22, 0xcf, 0x7a, 0x46, 0xe2, 0x91, 0xfc, 0xb7, 0x71, 0xe0, 0xbf,
	0x03, 0xfd, 0x3c, 0xe1, 0xdc, 0x1c, 0xd1, 0xb8, 0xf4, 0x50, 0x1f, 0x3d, 0xd4, 0x49, 0x0f, 0xf5,
	0xd2, 0x43, 0x57, 0xd2, 0x43, 0x0e, 0x3d, 0x6b, 0xb4, 0x87, 0xce, 0x68, 0x7f, 0x2c, 0x1e, 0x49,
	0xb2, 0x9c, 0xff, 0xbf, 0x53, 0xfa, 0x39, 0xe4, 0xed, 0xef, 0x7d, 0x0e, 0xb9, 0xeb, 0xd4, 0xa0,
	0xfb, 0x27, 0xd4, 0x95, 0x3b, 0x23, 0x8c, 0x39, 0x67, 0x75, 0x17, 0xb6, 0x2e, 0xf2, 0xe2, 0x15,
	0xa1, 0x15, 0xcd, 0x8b, 0x5a, 0xf5, 0xd6, 0x76, 0xf1, 0xac, 0xb9, 0x38, 0x9e, 0xbc, 0x22, 0x45,
	0xad, 0x5a, 0x6c, 0x1c, 0xd1, 0x0b, 0xb8, 0x25, 0x0a, 0xf4, 0xa4, 0xc8, 0xb4, 0x20, 0x45, 0xc7,
	0xb7, 0xf6, 0x66, 0xce, 0x43, 0xc2, 0x0f, 0x3c, 0x3b, 0xf5, 0x76, 0x1d, 0x6f, 0x24, 0x2d, 0xa4,
	0xe8, 0x14, 0x26, 0xda, 0xd7, 0x28, 0x66, 0x6b, 0xef, 0xf3, 0xf5, 0x90, 0xf9, 0x8e, 0xe3, 0x8d,
	0xc4, 0x41, 0xe0, 0x7c, 0x45, 0xcb, 0x6c, 0xbe, 0xa3, 0x75, 0xf8, 0x1e, 0x7a, 0xbb, 0x38, 0x5f,
	0x1f, 0x89, 0xf3, 0xd5, 0x3e, 0xc1, 0x37, 0x5c, 0x87, 0xef, 0xa1, 0xb5, 0x83, 0xf3, 0xb5, 0x11,
	0xa2, 0xef, 0x20, 0xac, 0xcb, 0x37, 0xa4, 0x60, 0xf1, 0xa6, 0xc0, 0xfa, 0xec, 0x6a, 0xac, 0x9f,
	0xc5, 0xda, 0xe3, 0x8d, 0x44, 0xed, 0x9a, 0x1e, 0xc0, 0x2d, 0xbf, 0xd2, 0x3d, 0x33, 0xcd, 0x3e,
	0x43, 0x03, 0xf7, 0x88, 0x4f, 0x1f, 0xc1, 0xc4, 0xae, 0xea, 0xfa, 0x53, 0x91, 0xc7, 0xf7, 0x2b,
	0xd7, 0xf3, 0xbe, 0x5a, 0x11, 0xdf, 0xae, 0xd2, 0xfa, 0x2f, 0xb4, 0xe9, 0x4f, 0x10, 0xca, 0x9a,
	0x70, 0xa5, 0xa7, 0xf3, 0x39, 0x61, 0x4c, 0xd8, 0x5a, 0xe9, 0x96, 0x2b, 0xc2, 0x30, 0xa1, 0xe4,
	0x82, 0x12, 0xf6, 0x5a, 0x2e, 0x91, 0x38, 0x8e, 0x6f, 0x3f, 0x94, 0x07, 0x0f, 0xff, 0x1b, 0xe8,
	0x89, 0xa4, 0x7a, 0xd0, 0x79, 0xb5, 0x77, 0x3f, 0xf6, 0x9c, 0x7b, 0x64, 0xe0, 0xdf, 0x23, 0xd6,
	0x4c, 0xb2, 0xee, 0xab, 0xab, 0x6f, 0x26, 0xbb, 0x76, 0x23, 0xef, 0xfe, 0xf3, 0x4e, 0xb8, 0xbc,
	0x9c, 0xfa, 0x4f, 0xf8, 0xa6, 0xc4, 0x6e, 0x1c, 0xf8, 0xa5, 0x9e, 0x86, 0x8d, 0xd8, 0x9a, 0xf4,
	0xfc, 0x82, 0x05, 0xed, 0x82, 0xf9, 0x65, 0x1f, 0xb4, 0xca, 0x8e, 0x9f, 0xc1, 0xed, 0x23, 0x52,
	0x9f, 0x91, 0x39, 0x25, 0xf5, 0x75, 0xbf, 0x23, 0xe5, 0xa0, 0x94, 0xb3, 0x4c, 0x0d, 0xca, 0x3f,
	0x83, 0xe6, 0xf3, 0xe4, 0x3c, 0x27, 0x97, 0xd7, 0x45, 0x96, 0x5f, 0x5d, 0xaa, 0x17, 0xc2, 0xe0,
	0x37, 0xbd, 0x28, 0x3d, 0x53, 0x8d, 0x50, 0x96, 0x98, 0x00, 0xbc, 0x8d, 0x4c, 0xf5, 0x40, 0x59,
	0xf8, 0x7b, 0xd8, 0xd1, 0x57, 0xb8, 0xc7, 0xe4, 0xca, 0x6f, 0x16, 0x77, 0xad, 0xbc, 0xca, 0x7f,
	0x0b, 0xc5, 0xd7, 0xfd, 0xd7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x83, 0x59, 0x71, 0x64, 0xea,
	0x0f, 0x00, 0x00,
}
