// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache.proto

package inout

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SecretCache struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretCache) Reset()         { *m = SecretCache{} }
func (m *SecretCache) String() string { return proto.CompactTextString(m) }
func (*SecretCache) ProtoMessage()    {}
func (*SecretCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_cache_baaa4b092b3c4017, []int{0}
}
func (m *SecretCache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretCache.Unmarshal(m, b)
}
func (m *SecretCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretCache.Marshal(b, m, deterministic)
}
func (dst *SecretCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretCache.Merge(dst, src)
}
func (m *SecretCache) XXX_Size() int {
	return xxx_messageInfo_SecretCache.Size(m)
}
func (m *SecretCache) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretCache.DiscardUnknown(m)
}

var xxx_messageInfo_SecretCache proto.InternalMessageInfo

func (m *SecretCache) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SecretCache) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SecretCache) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type UserViewCache struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Roles                []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Phones               []string `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	Emails               []string `protobuf:"bytes,5,rep,name=emails,proto3" json:"emails,omitempty"`
	RolesID              [][]byte `protobuf:"bytes,6,rep,name=rolesID,proto3" json:"rolesID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserViewCache) Reset()         { *m = UserViewCache{} }
func (m *UserViewCache) String() string { return proto.CompactTextString(m) }
func (*UserViewCache) ProtoMessage()    {}
func (*UserViewCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_cache_baaa4b092b3c4017, []int{1}
}
func (m *UserViewCache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserViewCache.Unmarshal(m, b)
}
func (m *UserViewCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserViewCache.Marshal(b, m, deterministic)
}
func (dst *UserViewCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserViewCache.Merge(dst, src)
}
func (m *UserViewCache) XXX_Size() int {
	return xxx_messageInfo_UserViewCache.Size(m)
}
func (m *UserViewCache) XXX_DiscardUnknown() {
	xxx_messageInfo_UserViewCache.DiscardUnknown(m)
}

var xxx_messageInfo_UserViewCache proto.InternalMessageInfo

func (m *UserViewCache) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UserViewCache) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *UserViewCache) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *UserViewCache) GetPhones() []string {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *UserViewCache) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *UserViewCache) GetRolesID() [][]byte {
	if m != nil {
		return m.RolesID
	}
	return nil
}

func init() {
	proto.RegisterType((*SecretCache)(nil), "inout.SecretCache")
	proto.RegisterType((*UserViewCache)(nil), "inout.UserViewCache")
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor_cache_baaa4b092b3c4017) }

var fileDescriptor_cache_baaa4b092b3c4017 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4e, 0x4c, 0xce,
	0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcc, 0xcb, 0x2f, 0x2d, 0x51, 0xf2,
	0xe5, 0xe2, 0x0e, 0x4e, 0x4d, 0x2e, 0x4a, 0x2d, 0x71, 0x06, 0xc9, 0x09, 0xf1, 0x71, 0x31, 0x65,
	0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x31, 0x65, 0xa6, 0x08, 0x49, 0x70, 0xb1, 0x27,
	0x17, 0xa5, 0x26, 0x96, 0xa4, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x30, 0x07, 0xc1, 0xb8, 0x42,
	0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0xcc, 0x60, 0xc5, 0x10, 0x8e, 0xd2, 0x4c,
	0x46, 0x2e, 0xde, 0xd0, 0xe2, 0xd4, 0xa2, 0xb0, 0xcc, 0xd4, 0x72, 0x32, 0x4c, 0x2c, 0xca, 0xcf,
	0x49, 0x2d, 0x96, 0x60, 0x56, 0x60, 0xd6, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0xc4, 0xb8, 0xd8, 0x0a,
	0x32, 0xf2, 0xf3, 0x52, 0x8b, 0x25, 0x58, 0xc0, 0xc2, 0x50, 0x1e, 0x48, 0x3c, 0x35, 0x37, 0x31,
	0x33, 0xa7, 0x58, 0x82, 0x15, 0x22, 0x0e, 0xe1, 0x81, 0xcc, 0x07, 0x6b, 0xf4, 0x74, 0x91, 0x60,
	0x53, 0x60, 0xd6, 0xe0, 0x09, 0x82, 0x71, 0x93, 0xd8, 0xc0, 0x1e, 0x37, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x2d, 0x8a, 0x50, 0x19, 0x07, 0x01, 0x00, 0x00,
}
