// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inout.proto

package inout

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRoleRequestV1 struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleRequestV1) Reset()         { *m = CreateRoleRequestV1{} }
func (m *CreateRoleRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRequestV1) ProtoMessage()    {}
func (*CreateRoleRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{0}
}
func (m *CreateRoleRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleRequestV1.Unmarshal(m, b)
}
func (m *CreateRoleRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateRoleRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleRequestV1.Merge(dst, src)
}
func (m *CreateRoleRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateRoleRequestV1.Size(m)
}
func (m *CreateRoleRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleRequestV1 proto.InternalMessageInfo

func (m *CreateRoleRequestV1) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateRoleBadRequestV1 struct {
	Title                []string `protobuf:"bytes,1,rep,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleBadRequestV1) Reset()         { *m = CreateRoleBadRequestV1{} }
func (m *CreateRoleBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateRoleBadRequestV1) ProtoMessage()    {}
func (*CreateRoleBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{1}
}
func (m *CreateRoleBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleBadRequestV1.Unmarshal(m, b)
}
func (m *CreateRoleBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateRoleBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleBadRequestV1.Merge(dst, src)
}
func (m *CreateRoleBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateRoleBadRequestV1.Size(m)
}
func (m *CreateRoleBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleBadRequestV1 proto.InternalMessageInfo

func (m *CreateRoleBadRequestV1) GetTitle() []string {
	if m != nil {
		return m.Title
	}
	return nil
}

type GetRoleResponseV1 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleResponseV1) Reset()         { *m = GetRoleResponseV1{} }
func (m *GetRoleResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetRoleResponseV1) ProtoMessage()    {}
func (*GetRoleResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{2}
}
func (m *GetRoleResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleResponseV1.Unmarshal(m, b)
}
func (m *GetRoleResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleResponseV1.Marshal(b, m, deterministic)
}
func (dst *GetRoleResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleResponseV1.Merge(dst, src)
}
func (m *GetRoleResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetRoleResponseV1.Size(m)
}
func (m *GetRoleResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleResponseV1 proto.InternalMessageInfo

func (m *GetRoleResponseV1) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetRoleResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *GetRoleResponseV1) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ListRoleResponseV1 struct {
	Data                 []*GetRoleResponseV1 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListRoleResponseV1) Reset()         { *m = ListRoleResponseV1{} }
func (m *ListRoleResponseV1) String() string { return proto.CompactTextString(m) }
func (*ListRoleResponseV1) ProtoMessage()    {}
func (*ListRoleResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{3}
}
func (m *ListRoleResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoleResponseV1.Unmarshal(m, b)
}
func (m *ListRoleResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoleResponseV1.Marshal(b, m, deterministic)
}
func (dst *ListRoleResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoleResponseV1.Merge(dst, src)
}
func (m *ListRoleResponseV1) XXX_Size() int {
	return xxx_messageInfo_ListRoleResponseV1.Size(m)
}
func (m *ListRoleResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoleResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoleResponseV1 proto.InternalMessageInfo

func (m *ListRoleResponseV1) GetData() []*GetRoleResponseV1 {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateUserRoleRequestV1 struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId               int64    `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRoleRequestV1) Reset()         { *m = CreateUserRoleRequestV1{} }
func (m *CreateUserRoleRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserRoleRequestV1) ProtoMessage()    {}
func (*CreateUserRoleRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{4}
}
func (m *CreateUserRoleRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRoleRequestV1.Unmarshal(m, b)
}
func (m *CreateUserRoleRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRoleRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserRoleRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRoleRequestV1.Merge(dst, src)
}
func (m *CreateUserRoleRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserRoleRequestV1.Size(m)
}
func (m *CreateUserRoleRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRoleRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRoleRequestV1 proto.InternalMessageInfo

func (m *CreateUserRoleRequestV1) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateUserRoleRequestV1) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type CreateUserRoleBadRequestV1 struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId               int64    `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Errors               []string `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRoleBadRequestV1) Reset()         { *m = CreateUserRoleBadRequestV1{} }
func (m *CreateUserRoleBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserRoleBadRequestV1) ProtoMessage()    {}
func (*CreateUserRoleBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{5}
}
func (m *CreateUserRoleBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRoleBadRequestV1.Unmarshal(m, b)
}
func (m *CreateUserRoleBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRoleBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserRoleBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRoleBadRequestV1.Merge(dst, src)
}
func (m *CreateUserRoleBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserRoleBadRequestV1.Size(m)
}
func (m *CreateUserRoleBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRoleBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRoleBadRequestV1 proto.InternalMessageInfo

func (m *CreateUserRoleBadRequestV1) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateUserRoleBadRequestV1) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *CreateUserRoleBadRequestV1) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type CreateUserRolesRequestV1 struct {
	UserRoles            []*CreateUserRoleRequestV1 `protobuf:"bytes,1,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreateUserRolesRequestV1) Reset()         { *m = CreateUserRolesRequestV1{} }
func (m *CreateUserRolesRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserRolesRequestV1) ProtoMessage()    {}
func (*CreateUserRolesRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{6}
}
func (m *CreateUserRolesRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRolesRequestV1.Unmarshal(m, b)
}
func (m *CreateUserRolesRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRolesRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserRolesRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRolesRequestV1.Merge(dst, src)
}
func (m *CreateUserRolesRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserRolesRequestV1.Size(m)
}
func (m *CreateUserRolesRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRolesRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRolesRequestV1 proto.InternalMessageInfo

func (m *CreateUserRolesRequestV1) GetUserRoles() []*CreateUserRoleRequestV1 {
	if m != nil {
		return m.UserRoles
	}
	return nil
}

type CreateUserRolesBadRequestV1 struct {
	Errors               []*CreateUserRoleBadRequestV1 `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CreateUserRolesBadRequestV1) Reset()         { *m = CreateUserRolesBadRequestV1{} }
func (m *CreateUserRolesBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserRolesBadRequestV1) ProtoMessage()    {}
func (*CreateUserRolesBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{7}
}
func (m *CreateUserRolesBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRolesBadRequestV1.Unmarshal(m, b)
}
func (m *CreateUserRolesBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRolesBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserRolesBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRolesBadRequestV1.Merge(dst, src)
}
func (m *CreateUserRolesBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserRolesBadRequestV1.Size(m)
}
func (m *CreateUserRolesBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRolesBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRolesBadRequestV1 proto.InternalMessageInfo

func (m *CreateUserRolesBadRequestV1) GetErrors() []*CreateUserRoleBadRequestV1 {
	if m != nil {
		return m.Errors
	}
	return nil
}

type CreateEmailRequestV1 struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailRequestV1) Reset()         { *m = CreateEmailRequestV1{} }
func (m *CreateEmailRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailRequestV1) ProtoMessage()    {}
func (*CreateEmailRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{8}
}
func (m *CreateEmailRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailRequestV1.Unmarshal(m, b)
}
func (m *CreateEmailRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailRequestV1.Merge(dst, src)
}
func (m *CreateEmailRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailRequestV1.Size(m)
}
func (m *CreateEmailRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailRequestV1 proto.InternalMessageInfo

func (m *CreateEmailRequestV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateEmailRequestV1) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateEmailRequestV1) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreateEmailBadRequestV1 struct {
	Email                []string `protobuf:"bytes,1,rep,name=email,proto3" json:"email,omitempty"`
	Code                 []string `protobuf:"bytes,2,rep,name=code,proto3" json:"code,omitempty"`
	UserId               []string `protobuf:"bytes,3,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailBadRequestV1) Reset()         { *m = CreateEmailBadRequestV1{} }
func (m *CreateEmailBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailBadRequestV1) ProtoMessage()    {}
func (*CreateEmailBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{9}
}
func (m *CreateEmailBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailBadRequestV1.Unmarshal(m, b)
}
func (m *CreateEmailBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailBadRequestV1.Merge(dst, src)
}
func (m *CreateEmailBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailBadRequestV1.Size(m)
}
func (m *CreateEmailBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailBadRequestV1 proto.InternalMessageInfo

func (m *CreateEmailBadRequestV1) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *CreateEmailBadRequestV1) GetCode() []string {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CreateEmailBadRequestV1) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

type CreateEmailResponseV1 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailResponseV1) Reset()         { *m = CreateEmailResponseV1{} }
func (m *CreateEmailResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailResponseV1) ProtoMessage()    {}
func (*CreateEmailResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{10}
}
func (m *CreateEmailResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailResponseV1.Unmarshal(m, b)
}
func (m *CreateEmailResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailResponseV1.Merge(dst, src)
}
func (m *CreateEmailResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailResponseV1.Size(m)
}
func (m *CreateEmailResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailResponseV1 proto.InternalMessageInfo

func (m *CreateEmailResponseV1) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateEmailResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CreateEmailResponseV1) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateEmailResponseV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateEmailConfirmationRequestV1 struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailConfirmationRequestV1) Reset()         { *m = CreateEmailConfirmationRequestV1{} }
func (m *CreateEmailConfirmationRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailConfirmationRequestV1) ProtoMessage()    {}
func (*CreateEmailConfirmationRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{11}
}
func (m *CreateEmailConfirmationRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailConfirmationRequestV1.Unmarshal(m, b)
}
func (m *CreateEmailConfirmationRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailConfirmationRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailConfirmationRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailConfirmationRequestV1.Merge(dst, src)
}
func (m *CreateEmailConfirmationRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailConfirmationRequestV1.Size(m)
}
func (m *CreateEmailConfirmationRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailConfirmationRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailConfirmationRequestV1 proto.InternalMessageInfo

func (m *CreateEmailConfirmationRequestV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateEmailConfirmationBadRequestV1 struct {
	Email                []string `protobuf:"bytes,1,rep,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailConfirmationBadRequestV1) Reset()         { *m = CreateEmailConfirmationBadRequestV1{} }
func (m *CreateEmailConfirmationBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailConfirmationBadRequestV1) ProtoMessage()    {}
func (*CreateEmailConfirmationBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{12}
}
func (m *CreateEmailConfirmationBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailConfirmationBadRequestV1.Unmarshal(m, b)
}
func (m *CreateEmailConfirmationBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailConfirmationBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailConfirmationBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailConfirmationBadRequestV1.Merge(dst, src)
}
func (m *CreateEmailConfirmationBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailConfirmationBadRequestV1.Size(m)
}
func (m *CreateEmailConfirmationBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailConfirmationBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailConfirmationBadRequestV1 proto.InternalMessageInfo

func (m *CreateEmailConfirmationBadRequestV1) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

type CreateEmailConfirmationResponseV1 struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Expire               int64    `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailConfirmationResponseV1) Reset()         { *m = CreateEmailConfirmationResponseV1{} }
func (m *CreateEmailConfirmationResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailConfirmationResponseV1) ProtoMessage()    {}
func (*CreateEmailConfirmationResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{13}
}
func (m *CreateEmailConfirmationResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailConfirmationResponseV1.Unmarshal(m, b)
}
func (m *CreateEmailConfirmationResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailConfirmationResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailConfirmationResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailConfirmationResponseV1.Merge(dst, src)
}
func (m *CreateEmailConfirmationResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailConfirmationResponseV1.Size(m)
}
func (m *CreateEmailConfirmationResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailConfirmationResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailConfirmationResponseV1 proto.InternalMessageInfo

func (m *CreateEmailConfirmationResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CreateEmailConfirmationResponseV1) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *CreateEmailConfirmationResponseV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreatePhoneRequestV1 struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneRequestV1) Reset()         { *m = CreatePhoneRequestV1{} }
func (m *CreatePhoneRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneRequestV1) ProtoMessage()    {}
func (*CreatePhoneRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{14}
}
func (m *CreatePhoneRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneRequestV1.Unmarshal(m, b)
}
func (m *CreatePhoneRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneRequestV1.Merge(dst, src)
}
func (m *CreatePhoneRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneRequestV1.Size(m)
}
func (m *CreatePhoneRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneRequestV1 proto.InternalMessageInfo

func (m *CreatePhoneRequestV1) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreatePhoneRequestV1) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreatePhoneRequestV1) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreatePhoneBadRequestV1 struct {
	Phone                []string `protobuf:"bytes,1,rep,name=phone,proto3" json:"phone,omitempty"`
	Code                 []string `protobuf:"bytes,2,rep,name=code,proto3" json:"code,omitempty"`
	UserId               []string `protobuf:"bytes,3,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneBadRequestV1) Reset()         { *m = CreatePhoneBadRequestV1{} }
func (m *CreatePhoneBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneBadRequestV1) ProtoMessage()    {}
func (*CreatePhoneBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{15}
}
func (m *CreatePhoneBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneBadRequestV1.Unmarshal(m, b)
}
func (m *CreatePhoneBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneBadRequestV1.Merge(dst, src)
}
func (m *CreatePhoneBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneBadRequestV1.Size(m)
}
func (m *CreatePhoneBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneBadRequestV1 proto.InternalMessageInfo

func (m *CreatePhoneBadRequestV1) GetPhone() []string {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *CreatePhoneBadRequestV1) GetCode() []string {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CreatePhoneBadRequestV1) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

type CreatePhoneResponseV1 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneResponseV1) Reset()         { *m = CreatePhoneResponseV1{} }
func (m *CreatePhoneResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneResponseV1) ProtoMessage()    {}
func (*CreatePhoneResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{16}
}
func (m *CreatePhoneResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneResponseV1.Unmarshal(m, b)
}
func (m *CreatePhoneResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneResponseV1.Merge(dst, src)
}
func (m *CreatePhoneResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneResponseV1.Size(m)
}
func (m *CreatePhoneResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneResponseV1 proto.InternalMessageInfo

func (m *CreatePhoneResponseV1) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreatePhoneResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CreatePhoneResponseV1) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreatePhoneResponseV1) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type CreatePhoneConfirmationRequestV1 struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneConfirmationRequestV1) Reset()         { *m = CreatePhoneConfirmationRequestV1{} }
func (m *CreatePhoneConfirmationRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneConfirmationRequestV1) ProtoMessage()    {}
func (*CreatePhoneConfirmationRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{17}
}
func (m *CreatePhoneConfirmationRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneConfirmationRequestV1.Unmarshal(m, b)
}
func (m *CreatePhoneConfirmationRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneConfirmationRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneConfirmationRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneConfirmationRequestV1.Merge(dst, src)
}
func (m *CreatePhoneConfirmationRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneConfirmationRequestV1.Size(m)
}
func (m *CreatePhoneConfirmationRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneConfirmationRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneConfirmationRequestV1 proto.InternalMessageInfo

func (m *CreatePhoneConfirmationRequestV1) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type CreatePhoneConfirmationBadRequestV1 struct {
	Phone                []string `protobuf:"bytes,1,rep,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneConfirmationBadRequestV1) Reset()         { *m = CreatePhoneConfirmationBadRequestV1{} }
func (m *CreatePhoneConfirmationBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneConfirmationBadRequestV1) ProtoMessage()    {}
func (*CreatePhoneConfirmationBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{18}
}
func (m *CreatePhoneConfirmationBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneConfirmationBadRequestV1.Unmarshal(m, b)
}
func (m *CreatePhoneConfirmationBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneConfirmationBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneConfirmationBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneConfirmationBadRequestV1.Merge(dst, src)
}
func (m *CreatePhoneConfirmationBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneConfirmationBadRequestV1.Size(m)
}
func (m *CreatePhoneConfirmationBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneConfirmationBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneConfirmationBadRequestV1 proto.InternalMessageInfo

func (m *CreatePhoneConfirmationBadRequestV1) GetPhone() []string {
	if m != nil {
		return m.Phone
	}
	return nil
}

type CreatePhoneConfirmationResponseV1 struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Expire               int64    `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneConfirmationResponseV1) Reset()         { *m = CreatePhoneConfirmationResponseV1{} }
func (m *CreatePhoneConfirmationResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneConfirmationResponseV1) ProtoMessage()    {}
func (*CreatePhoneConfirmationResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{19}
}
func (m *CreatePhoneConfirmationResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneConfirmationResponseV1.Unmarshal(m, b)
}
func (m *CreatePhoneConfirmationResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneConfirmationResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneConfirmationResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneConfirmationResponseV1.Merge(dst, src)
}
func (m *CreatePhoneConfirmationResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneConfirmationResponseV1.Size(m)
}
func (m *CreatePhoneConfirmationResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneConfirmationResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneConfirmationResponseV1 proto.InternalMessageInfo

func (m *CreatePhoneConfirmationResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CreatePhoneConfirmationResponseV1) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *CreatePhoneConfirmationResponseV1) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type CreatePasswordRequestV1 struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordRequestV1) Reset()         { *m = CreatePasswordRequestV1{} }
func (m *CreatePasswordRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordRequestV1) ProtoMessage()    {}
func (*CreatePasswordRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{20}
}
func (m *CreatePasswordRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordRequestV1.Unmarshal(m, b)
}
func (m *CreatePasswordRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreatePasswordRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordRequestV1.Merge(dst, src)
}
func (m *CreatePasswordRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordRequestV1.Size(m)
}
func (m *CreatePasswordRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordRequestV1 proto.InternalMessageInfo

func (m *CreatePasswordRequestV1) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreatePasswordRequestV1) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CreatePasswordBadRequestResponseV1 struct {
	UserId               []string `protobuf:"bytes,1,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Value                []string `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordBadRequestResponseV1) Reset()         { *m = CreatePasswordBadRequestResponseV1{} }
func (m *CreatePasswordBadRequestResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordBadRequestResponseV1) ProtoMessage()    {}
func (*CreatePasswordBadRequestResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{21}
}
func (m *CreatePasswordBadRequestResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordBadRequestResponseV1.Unmarshal(m, b)
}
func (m *CreatePasswordBadRequestResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordBadRequestResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreatePasswordBadRequestResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordBadRequestResponseV1.Merge(dst, src)
}
func (m *CreatePasswordBadRequestResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordBadRequestResponseV1.Size(m)
}
func (m *CreatePasswordBadRequestResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordBadRequestResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordBadRequestResponseV1 proto.InternalMessageInfo

func (m *CreatePasswordBadRequestResponseV1) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *CreatePasswordBadRequestResponseV1) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type CreatePasswordResponseV1 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordResponseV1) Reset()         { *m = CreatePasswordResponseV1{} }
func (m *CreatePasswordResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordResponseV1) ProtoMessage()    {}
func (*CreatePasswordResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{22}
}
func (m *CreatePasswordResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordResponseV1.Unmarshal(m, b)
}
func (m *CreatePasswordResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordResponseV1.Marshal(b, m, deterministic)
}
func (dst *CreatePasswordResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordResponseV1.Merge(dst, src)
}
func (m *CreatePasswordResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordResponseV1.Size(m)
}
func (m *CreatePasswordResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordResponseV1 proto.InternalMessageInfo

func (m *CreatePasswordResponseV1) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreatePasswordResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CreatePasswordResponseV1) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreateUserRequestV1 struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneCode            string   `protobuf:"bytes,4,opt,name=phoneCode,proto3" json:"phoneCode,omitempty"`
	EmailCode            string   `protobuf:"bytes,5,opt,name=emailCode,proto3" json:"emailCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequestV1) Reset()         { *m = CreateUserRequestV1{} }
func (m *CreateUserRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequestV1) ProtoMessage()    {}
func (*CreateUserRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{23}
}
func (m *CreateUserRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequestV1.Unmarshal(m, b)
}
func (m *CreateUserRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequestV1.Merge(dst, src)
}
func (m *CreateUserRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequestV1.Size(m)
}
func (m *CreateUserRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequestV1 proto.InternalMessageInfo

func (m *CreateUserRequestV1) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequestV1) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateUserRequestV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequestV1) GetPhoneCode() string {
	if m != nil {
		return m.PhoneCode
	}
	return ""
}

func (m *CreateUserRequestV1) GetEmailCode() string {
	if m != nil {
		return m.EmailCode
	}
	return ""
}

type CreateUserBadRequestV1 struct {
	Password             []string `protobuf:"bytes,1,rep,name=password,proto3" json:"password,omitempty"`
	Phone                []string `protobuf:"bytes,2,rep,name=phone,proto3" json:"phone,omitempty"`
	Email                []string `protobuf:"bytes,3,rep,name=email,proto3" json:"email,omitempty"`
	PhoneCode            []string `protobuf:"bytes,4,rep,name=phoneCode,proto3" json:"phoneCode,omitempty"`
	EmailCode            []string `protobuf:"bytes,5,rep,name=emailCode,proto3" json:"emailCode,omitempty"`
	Errors               []string `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserBadRequestV1) Reset()         { *m = CreateUserBadRequestV1{} }
func (m *CreateUserBadRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserBadRequestV1) ProtoMessage()    {}
func (*CreateUserBadRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{24}
}
func (m *CreateUserBadRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserBadRequestV1.Unmarshal(m, b)
}
func (m *CreateUserBadRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserBadRequestV1.Marshal(b, m, deterministic)
}
func (dst *CreateUserBadRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserBadRequestV1.Merge(dst, src)
}
func (m *CreateUserBadRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserBadRequestV1.Size(m)
}
func (m *CreateUserBadRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserBadRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserBadRequestV1 proto.InternalMessageInfo

func (m *CreateUserBadRequestV1) GetPassword() []string {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *CreateUserBadRequestV1) GetPhone() []string {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *CreateUserBadRequestV1) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *CreateUserBadRequestV1) GetPhoneCode() []string {
	if m != nil {
		return m.PhoneCode
	}
	return nil
}

func (m *CreateUserBadRequestV1) GetEmailCode() []string {
	if m != nil {
		return m.EmailCode
	}
	return nil
}

func (m *CreateUserBadRequestV1) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type GetUserResponseV1 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponseV1) Reset()         { *m = GetUserResponseV1{} }
func (m *GetUserResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetUserResponseV1) ProtoMessage()    {}
func (*GetUserResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{25}
}
func (m *GetUserResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponseV1.Unmarshal(m, b)
}
func (m *GetUserResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponseV1.Marshal(b, m, deterministic)
}
func (dst *GetUserResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponseV1.Merge(dst, src)
}
func (m *GetUserResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetUserResponseV1.Size(m)
}
func (m *GetUserResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponseV1 proto.InternalMessageInfo

func (m *GetUserResponseV1) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type ListUserResponseV1 struct {
	Data                 []*GetUserResponseV1 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListUserResponseV1) Reset()         { *m = ListUserResponseV1{} }
func (m *ListUserResponseV1) String() string { return proto.CompactTextString(m) }
func (*ListUserResponseV1) ProtoMessage()    {}
func (*ListUserResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{26}
}
func (m *ListUserResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResponseV1.Unmarshal(m, b)
}
func (m *ListUserResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResponseV1.Marshal(b, m, deterministic)
}
func (dst *ListUserResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResponseV1.Merge(dst, src)
}
func (m *ListUserResponseV1) XXX_Size() int {
	return xxx_messageInfo_ListUserResponseV1.Size(m)
}
func (m *ListUserResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResponseV1 proto.InternalMessageInfo

func (m *ListUserResponseV1) GetData() []*GetUserResponseV1 {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetUserViewResponseV1 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Roles                []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Phones               []string `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	Emails               []string `protobuf:"bytes,5,rep,name=emails,proto3" json:"emails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserViewResponseV1) Reset()         { *m = GetUserViewResponseV1{} }
func (m *GetUserViewResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetUserViewResponseV1) ProtoMessage()    {}
func (*GetUserViewResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{27}
}
func (m *GetUserViewResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserViewResponseV1.Unmarshal(m, b)
}
func (m *GetUserViewResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserViewResponseV1.Marshal(b, m, deterministic)
}
func (dst *GetUserViewResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserViewResponseV1.Merge(dst, src)
}
func (m *GetUserViewResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetUserViewResponseV1.Size(m)
}
func (m *GetUserViewResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserViewResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserViewResponseV1 proto.InternalMessageInfo

func (m *GetUserViewResponseV1) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserViewResponseV1) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *GetUserViewResponseV1) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *GetUserViewResponseV1) GetPhones() []string {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *GetUserViewResponseV1) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

type ListUserViewResponseV1 struct {
	Data                 []*GetUserViewResponseV1 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ListUserViewResponseV1) Reset()         { *m = ListUserViewResponseV1{} }
func (m *ListUserViewResponseV1) String() string { return proto.CompactTextString(m) }
func (*ListUserViewResponseV1) ProtoMessage()    {}
func (*ListUserViewResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{28}
}
func (m *ListUserViewResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserViewResponseV1.Unmarshal(m, b)
}
func (m *ListUserViewResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserViewResponseV1.Marshal(b, m, deterministic)
}
func (dst *ListUserViewResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserViewResponseV1.Merge(dst, src)
}
func (m *ListUserViewResponseV1) XXX_Size() int {
	return xxx_messageInfo_ListUserViewResponseV1.Size(m)
}
func (m *ListUserViewResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserViewResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserViewResponseV1 proto.InternalMessageInfo

func (m *ListUserViewResponseV1) GetData() []*GetUserViewResponseV1 {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateEmailConfirmationEventV1 struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailConfirmationEventV1) Reset()         { *m = CreateEmailConfirmationEventV1{} }
func (m *CreateEmailConfirmationEventV1) String() string { return proto.CompactTextString(m) }
func (*CreateEmailConfirmationEventV1) ProtoMessage()    {}
func (*CreateEmailConfirmationEventV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{29}
}
func (m *CreateEmailConfirmationEventV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailConfirmationEventV1.Unmarshal(m, b)
}
func (m *CreateEmailConfirmationEventV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailConfirmationEventV1.Marshal(b, m, deterministic)
}
func (dst *CreateEmailConfirmationEventV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailConfirmationEventV1.Merge(dst, src)
}
func (m *CreateEmailConfirmationEventV1) XXX_Size() int {
	return xxx_messageInfo_CreateEmailConfirmationEventV1.Size(m)
}
func (m *CreateEmailConfirmationEventV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailConfirmationEventV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailConfirmationEventV1 proto.InternalMessageInfo

func (m *CreateEmailConfirmationEventV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateEmailConfirmationEventV1) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type CreatePhoneConfirmationEventV1 struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneConfirmationEventV1) Reset()         { *m = CreatePhoneConfirmationEventV1{} }
func (m *CreatePhoneConfirmationEventV1) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneConfirmationEventV1) ProtoMessage()    {}
func (*CreatePhoneConfirmationEventV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{30}
}
func (m *CreatePhoneConfirmationEventV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneConfirmationEventV1.Unmarshal(m, b)
}
func (m *CreatePhoneConfirmationEventV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneConfirmationEventV1.Marshal(b, m, deterministic)
}
func (dst *CreatePhoneConfirmationEventV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneConfirmationEventV1.Merge(dst, src)
}
func (m *CreatePhoneConfirmationEventV1) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneConfirmationEventV1.Size(m)
}
func (m *CreatePhoneConfirmationEventV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneConfirmationEventV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneConfirmationEventV1 proto.InternalMessageInfo

func (m *CreatePhoneConfirmationEventV1) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreatePhoneConfirmationEventV1) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ChangedUserViewsEventV1 struct {
	Identifiers          []int64  `protobuf:"varint,1,rep,packed,name=identifiers,proto3" json:"identifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangedUserViewsEventV1) Reset()         { *m = ChangedUserViewsEventV1{} }
func (m *ChangedUserViewsEventV1) String() string { return proto.CompactTextString(m) }
func (*ChangedUserViewsEventV1) ProtoMessage()    {}
func (*ChangedUserViewsEventV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{31}
}
func (m *ChangedUserViewsEventV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangedUserViewsEventV1.Unmarshal(m, b)
}
func (m *ChangedUserViewsEventV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangedUserViewsEventV1.Marshal(b, m, deterministic)
}
func (dst *ChangedUserViewsEventV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangedUserViewsEventV1.Merge(dst, src)
}
func (m *ChangedUserViewsEventV1) XXX_Size() int {
	return xxx_messageInfo_ChangedUserViewsEventV1.Size(m)
}
func (m *ChangedUserViewsEventV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangedUserViewsEventV1.DiscardUnknown(m)
}

var xxx_messageInfo_ChangedUserViewsEventV1 proto.InternalMessageInfo

func (m *ChangedUserViewsEventV1) GetIdentifiers() []int64 {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

type Event struct {
	Sender       string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Object       string `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Action       string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	EventVersion string `protobuf:"bytes,4,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	DataVersion  string `protobuf:"bytes,5,opt,name=data_version,json=dataVersion,proto3" json:"data_version,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*Event_PhoneConfirmationEvent
	//	*Event_EmailConfirmationEvent
	//	*Event_ChangedUserViewsEvent
	Data                 isEvent_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_inout_f6c8aeeb3b5958a3, []int{32}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Event) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *Event) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Event) GetEventVersion() string {
	if m != nil {
		return m.EventVersion
	}
	return ""
}

func (m *Event) GetDataVersion() string {
	if m != nil {
		return m.DataVersion
	}
	return ""
}

type isEvent_Data interface {
	isEvent_Data()
}

type Event_PhoneConfirmationEvent struct {
	PhoneConfirmationEvent *CreatePhoneConfirmationEventV1 `protobuf:"bytes,6,opt,name=phoneConfirmationEvent,proto3,oneof"`
}

type Event_EmailConfirmationEvent struct {
	EmailConfirmationEvent *CreateEmailConfirmationEventV1 `protobuf:"bytes,7,opt,name=emailConfirmationEvent,proto3,oneof"`
}

type Event_ChangedUserViewsEvent struct {
	ChangedUserViewsEvent *ChangedUserViewsEventV1 `protobuf:"bytes,8,opt,name=changedUserViewsEvent,proto3,oneof"`
}

func (*Event_PhoneConfirmationEvent) isEvent_Data() {}

func (*Event_EmailConfirmationEvent) isEvent_Data() {}

func (*Event_ChangedUserViewsEvent) isEvent_Data() {}

func (m *Event) GetData() isEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetPhoneConfirmationEvent() *CreatePhoneConfirmationEventV1 {
	if x, ok := m.GetData().(*Event_PhoneConfirmationEvent); ok {
		return x.PhoneConfirmationEvent
	}
	return nil
}

func (m *Event) GetEmailConfirmationEvent() *CreateEmailConfirmationEventV1 {
	if x, ok := m.GetData().(*Event_EmailConfirmationEvent); ok {
		return x.EmailConfirmationEvent
	}
	return nil
}

func (m *Event) GetChangedUserViewsEvent() *ChangedUserViewsEventV1 {
	if x, ok := m.GetData().(*Event_ChangedUserViewsEvent); ok {
		return x.ChangedUserViewsEvent
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Event) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Event_OneofMarshaler, _Event_OneofUnmarshaler, _Event_OneofSizer, []interface{}{
		(*Event_PhoneConfirmationEvent)(nil),
		(*Event_EmailConfirmationEvent)(nil),
		(*Event_ChangedUserViewsEvent)(nil),
	}
}

func _Event_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Event)
	// data
	switch x := m.Data.(type) {
	case *Event_PhoneConfirmationEvent:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PhoneConfirmationEvent); err != nil {
			return err
		}
	case *Event_EmailConfirmationEvent:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EmailConfirmationEvent); err != nil {
			return err
		}
	case *Event_ChangedUserViewsEvent:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ChangedUserViewsEvent); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Event.Data has unexpected type %T", x)
	}
	return nil
}

func _Event_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Event)
	switch tag {
	case 6: // data.phoneConfirmationEvent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreatePhoneConfirmationEventV1)
		err := b.DecodeMessage(msg)
		m.Data = &Event_PhoneConfirmationEvent{msg}
		return true, err
	case 7: // data.emailConfirmationEvent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateEmailConfirmationEventV1)
		err := b.DecodeMessage(msg)
		m.Data = &Event_EmailConfirmationEvent{msg}
		return true, err
	case 8: // data.changedUserViewsEvent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChangedUserViewsEventV1)
		err := b.DecodeMessage(msg)
		m.Data = &Event_ChangedUserViewsEvent{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Event_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Event)
	// data
	switch x := m.Data.(type) {
	case *Event_PhoneConfirmationEvent:
		s := proto.Size(x.PhoneConfirmationEvent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_EmailConfirmationEvent:
		s := proto.Size(x.EmailConfirmationEvent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_ChangedUserViewsEvent:
		s := proto.Size(x.ChangedUserViewsEvent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*CreateRoleRequestV1)(nil), "inout.CreateRoleRequestV1")
	proto.RegisterType((*CreateRoleBadRequestV1)(nil), "inout.CreateRoleBadRequestV1")
	proto.RegisterType((*GetRoleResponseV1)(nil), "inout.GetRoleResponseV1")
	proto.RegisterType((*ListRoleResponseV1)(nil), "inout.ListRoleResponseV1")
	proto.RegisterType((*CreateUserRoleRequestV1)(nil), "inout.CreateUserRoleRequestV1")
	proto.RegisterType((*CreateUserRoleBadRequestV1)(nil), "inout.CreateUserRoleBadRequestV1")
	proto.RegisterType((*CreateUserRolesRequestV1)(nil), "inout.CreateUserRolesRequestV1")
	proto.RegisterType((*CreateUserRolesBadRequestV1)(nil), "inout.CreateUserRolesBadRequestV1")
	proto.RegisterType((*CreateEmailRequestV1)(nil), "inout.CreateEmailRequestV1")
	proto.RegisterType((*CreateEmailBadRequestV1)(nil), "inout.CreateEmailBadRequestV1")
	proto.RegisterType((*CreateEmailResponseV1)(nil), "inout.CreateEmailResponseV1")
	proto.RegisterType((*CreateEmailConfirmationRequestV1)(nil), "inout.CreateEmailConfirmationRequestV1")
	proto.RegisterType((*CreateEmailConfirmationBadRequestV1)(nil), "inout.CreateEmailConfirmationBadRequestV1")
	proto.RegisterType((*CreateEmailConfirmationResponseV1)(nil), "inout.CreateEmailConfirmationResponseV1")
	proto.RegisterType((*CreatePhoneRequestV1)(nil), "inout.CreatePhoneRequestV1")
	proto.RegisterType((*CreatePhoneBadRequestV1)(nil), "inout.CreatePhoneBadRequestV1")
	proto.RegisterType((*CreatePhoneResponseV1)(nil), "inout.CreatePhoneResponseV1")
	proto.RegisterType((*CreatePhoneConfirmationRequestV1)(nil), "inout.CreatePhoneConfirmationRequestV1")
	proto.RegisterType((*CreatePhoneConfirmationBadRequestV1)(nil), "inout.CreatePhoneConfirmationBadRequestV1")
	proto.RegisterType((*CreatePhoneConfirmationResponseV1)(nil), "inout.CreatePhoneConfirmationResponseV1")
	proto.RegisterType((*CreatePasswordRequestV1)(nil), "inout.CreatePasswordRequestV1")
	proto.RegisterType((*CreatePasswordBadRequestResponseV1)(nil), "inout.CreatePasswordBadRequestResponseV1")
	proto.RegisterType((*CreatePasswordResponseV1)(nil), "inout.CreatePasswordResponseV1")
	proto.RegisterType((*CreateUserRequestV1)(nil), "inout.CreateUserRequestV1")
	proto.RegisterType((*CreateUserBadRequestV1)(nil), "inout.CreateUserBadRequestV1")
	proto.RegisterType((*GetUserResponseV1)(nil), "inout.GetUserResponseV1")
	proto.RegisterType((*ListUserResponseV1)(nil), "inout.ListUserResponseV1")
	proto.RegisterType((*GetUserViewResponseV1)(nil), "inout.GetUserViewResponseV1")
	proto.RegisterType((*ListUserViewResponseV1)(nil), "inout.ListUserViewResponseV1")
	proto.RegisterType((*CreateEmailConfirmationEventV1)(nil), "inout.CreateEmailConfirmationEventV1")
	proto.RegisterType((*CreatePhoneConfirmationEventV1)(nil), "inout.CreatePhoneConfirmationEventV1")
	proto.RegisterType((*ChangedUserViewsEventV1)(nil), "inout.ChangedUserViewsEventV1")
	proto.RegisterType((*Event)(nil), "inout.Event")
}

func init() { proto.RegisterFile("inout.proto", fileDescriptor_inout_f6c8aeeb3b5958a3) }

var fileDescriptor_inout_f6c8aeeb3b5958a3 = []byte{
	// 862 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdf, 0x4e, 0x13, 0x4f,
	0x14, 0xa6, 0x9d, 0xb6, 0xd0, 0x53, 0x7e, 0xbf, 0xc4, 0x15, 0xca, 0x06, 0x09, 0x29, 0x43, 0x4c,
	0x48, 0x34, 0x44, 0xf0, 0x46, 0x43, 0xb8, 0x81, 0x10, 0x01, 0xbd, 0x30, 0x4b, 0x6c, 0x34, 0xd1,
	0x90, 0xa5, 0x3b, 0xc8, 0x6a, 0xd9, 0x5d, 0x77, 0xb6, 0xe0, 0x1b, 0xf8, 0x0c, 0xbe, 0x87, 0x37,
	0xbe, 0x9d, 0x99, 0x7f, 0x3b, 0x33, 0xed, 0xac, 0x50, 0xe4, 0xae, 0xe7, 0xcc, 0xd9, 0xef, 0x7c,
	0xe7, 0x3b, 0x67, 0xfe, 0x14, 0x3a, 0x71, 0x92, 0x8e, 0x8a, 0xcd, 0x2c, 0x4f, 0x8b, 0xd4, 0x6b,
	0x72, 0x03, 0x3f, 0x81, 0x87, 0xfb, 0x39, 0x09, 0x0b, 0x12, 0xa4, 0x43, 0x12, 0x90, 0x6f, 0x23,
	0x42, 0x8b, 0xfe, 0x96, 0xb7, 0x00, 0xcd, 0x22, 0x2e, 0x86, 0xc4, 0xaf, 0xf5, 0x6a, 0x1b, 0xed,
	0x40, 0x18, 0x78, 0x13, 0xba, 0x3a, 0x78, 0x2f, 0x8c, 0x9c, 0xf1, 0x48, 0xc7, 0x9f, 0xc0, 0x83,
	0x57, 0xa4, 0x10, 0xc8, 0x34, 0x4b, 0x13, 0x4a, 0xfa, 0x5b, 0xde, 0xff, 0x50, 0x8f, 0x23, 0x8e,
	0x8b, 0x82, 0x7a, 0x1c, 0x79, 0x3e, 0xcc, 0x0e, 0x38, 0x68, 0xe4, 0xd7, 0xb9, 0x53, 0x99, 0x1a,
	0x14, 0x99, 0x24, 0xf6, 0xc0, 0x7b, 0x13, 0xd3, 0x71, 0xd4, 0xa7, 0xd0, 0x88, 0xc2, 0x22, 0xe4,
	0xf9, 0x3b, 0xdb, 0xfe, 0xa6, 0x28, 0x75, 0x22, 0x7b, 0xc0, 0xa3, 0xf0, 0x6b, 0x58, 0x12, 0x85,
	0xbc, 0xa3, 0x24, 0xb7, 0x2b, 0x5f, 0x82, 0xd9, 0x11, 0x25, 0xf9, 0x69, 0xc9, 0xb1, 0xc5, 0xcc,
	0xa3, 0x88, 0x2d, 0xe4, 0xe9, 0x90, 0xb0, 0x05, 0xc1, 0xb3, 0xc5, 0xcc, 0xa3, 0x08, 0x9f, 0xc3,
	0xb2, 0x0d, 0x66, 0x29, 0x33, 0x35, 0x9e, 0xd7, 0x85, 0x16, 0xc9, 0xf3, 0x34, 0xa7, 0x3e, 0xe2,
	0x62, 0x4a, 0x0b, 0x7f, 0x00, 0xdf, 0xce, 0x43, 0x75, 0x96, 0x5d, 0x00, 0x9e, 0x85, 0x41, 0x50,
	0x29, 0xc2, 0xaa, 0x14, 0xa1, 0xa2, 0xd2, 0xa0, 0x3d, 0x52, 0x38, 0xf8, 0x3d, 0x3c, 0x1a, 0x83,
	0xb6, 0x6a, 0x78, 0x59, 0x32, 0x12, 0xc8, 0x6b, 0x4e, 0x64, 0xf3, 0x13, 0x83, 0xf4, 0x82, 0x88,
	0x3a, 0xb8, 0x0c, 0xe3, 0xa1, 0x35, 0x30, 0x84, 0x79, 0xd4, 0x80, 0x71, 0xc3, 0xf3, 0xa0, 0x31,
	0x48, 0x23, 0xc2, 0x05, 0x69, 0x07, 0xfc, 0xb7, 0x29, 0x20, 0x32, 0x05, 0xc4, 0x1f, 0x55, 0x13,
	0x39, 0xf4, 0xf8, 0x38, 0x2a, 0x74, 0xe4, 0x42, 0x47, 0x6e, 0x74, 0xae, 0xb6, 0x44, 0xcf, 0x60,
	0xd1, 0x22, 0x7e, 0x87, 0xf9, 0xad, 0x62, 0xae, 0xe9, 0x35, 0x8c, 0xe2, 0xf1, 0x0b, 0xe8, 0x19,
	0x19, 0xf7, 0xd3, 0xe4, 0x3c, 0xce, 0x2f, 0xc3, 0x22, 0x4e, 0x93, 0x1b, 0x64, 0xc3, 0x3b, 0xb0,
	0x5e, 0xf1, 0xe5, 0xcd, 0xaa, 0xe0, 0xaf, 0xb0, 0x56, 0x99, 0xb6, 0x2c, 0xda, 0x28, 0xb2, 0x66,
	0x17, 0xc9, 0xa6, 0xf5, 0x7b, 0x16, 0xe7, 0x44, 0x4d, 0xb1, 0xb0, 0x74, 0x32, 0x64, 0x32, 0x2d,
	0xc7, 0xe1, 0xed, 0x45, 0x9a, 0xd8, 0xe7, 0x4d, 0xc6, 0x3c, 0xaa, 0x2e, 0x6e, 0xdc, 0x71, 0x1c,
	0x38, 0xf4, 0x78, 0xe1, 0x0a, 0x1d, 0xb9, 0xd0, 0xa7, 0x19, 0x07, 0x49, 0xfc, 0x9e, 0xc7, 0x41,
	0xd0, 0x6b, 0x18, 0xc5, 0xeb, 0x71, 0xe0, 0x19, 0x2b, 0xc7, 0x61, 0x52, 0x36, 0x3d, 0x0e, 0x13,
	0x5f, 0xde, 0xac, 0x8a, 0x1e, 0x07, 0x47, 0xda, 0x7f, 0x1b, 0x07, 0x91, 0x0c, 0x99, 0x4c, 0x0f,
	0xcb, 0x9e, 0x85, 0x94, 0x5e, 0xa7, 0xf9, 0x6d, 0xce, 0xcd, 0x05, 0x68, 0x5e, 0x85, 0xc3, 0x91,
	0x9a, 0x0a, 0x61, 0xe0, 0x13, 0xc0, 0x36, 0x92, 0x2e, 0xd5, 0xe0, 0x6d, 0x81, 0x1a, 0xed, 0x35,
	0x41, 0x91, 0x06, 0xfd, 0xa4, 0x4e, 0x5c, 0x4d, 0xef, 0x1e, 0xfb, 0x8e, 0x7f, 0xd6, 0xd4, 0xe5,
	0xcb, 0x8f, 0xd0, 0xb2, 0xf4, 0x65, 0x98, 0xcb, 0x64, 0x42, 0xd9, 0xd8, 0xd2, 0xd6, 0x3a, 0xd6,
	0xcd, 0x8d, 0xe2, 0xdc, 0x6c, 0xde, 0x0a, 0xb4, 0x33, 0xd1, 0xc4, 0x48, 0xcd, 0x96, 0x76, 0xb0,
	0x55, 0x22, 0x76, 0x7c, 0x44, 0xfc, 0xa6, 0x58, 0x2d, 0x1d, 0xf8, 0x57, 0x4d, 0xdd, 0xf5, 0x8c,
	0x9b, 0x35, 0x37, 0x36, 0x3d, 0x54, 0x45, 0x0f, 0x39, 0xe9, 0xa1, 0x4a, 0x7a, 0xe8, 0xaf, 0xf4,
	0x90, 0x45, 0xcf, 0xb8, 0x23, 0x5b, 0xd6, 0x1d, 0xb9, 0xcb, 0x5f, 0x1c, 0x42, 0xce, 0xe9, 0x5b,
	0xa5, 0xde, 0x16, 0x63, 0xdf, 0x57, 0xbe, 0x2d, 0xec, 0x38, 0xf9, 0xb6, 0xf8, 0x51, 0x83, 0x45,
	0xb9, 0xd6, 0x8f, 0xc9, 0xf5, 0x5d, 0x5f, 0x3e, 0xe2, 0x26, 0x97, 0x82, 0x71, 0x83, 0x15, 0xcd,
	0xf5, 0xa1, 0x52, 0x2d, 0x69, 0x71, 0x31, 0x98, 0x32, 0x54, 0xea, 0x24, 0x2d, 0x7c, 0x0c, 0x5d,
	0x55, 0xcd, 0x18, 0x93, 0x67, 0x56, 0x45, 0x2b, 0x76, 0x45, 0x76, 0xac, 0xac, 0xea, 0x18, 0x56,
	0x2b, 0x6e, 0x89, 0x83, 0x2b, 0x92, 0x4c, 0x75, 0xa3, 0x6b, 0xac, 0x89, 0x23, 0xc6, 0xc0, 0xba,
	0xdd, 0x75, 0x80, 0x77, 0x60, 0x69, 0xff, 0x22, 0x4c, 0x3e, 0x93, 0x48, 0x51, 0xa7, 0x0a, 0xa4,
	0x07, 0x9d, 0x38, 0x22, 0x49, 0x11, 0x9f, 0xc7, 0x44, 0x3e, 0x5d, 0x50, 0x60, 0xba, 0xf0, 0x6f,
	0x04, 0x4d, 0x1e, 0xcd, 0x24, 0xa4, 0x24, 0x89, 0x48, 0x2e, 0x33, 0x4a, 0x8b, 0xf9, 0xd3, 0xb3,
	0x2f, 0x64, 0x50, 0xc8, 0xa4, 0xd2, 0x62, 0xfe, 0x70, 0xc0, 0x18, 0xcb, 0x1d, 0x27, 0x2d, 0x6f,
	0x1d, 0xfe, 0x23, 0x0c, 0xf0, 0xf4, 0x8a, 0xe4, 0x94, 0x2d, 0x8b, 0x6d, 0x37, 0xcf, 0x9d, 0x7d,
	0xe1, 0xf3, 0xd6, 0x60, 0x9e, 0x69, 0x5a, 0xc6, 0x88, 0xcd, 0xd7, 0x61, 0x3e, 0x15, 0x72, 0x0a,
	0xdd, 0xcc, 0x29, 0x8e, 0xdf, 0xea, 0xd5, 0x36, 0x3a, 0xdb, 0x8f, 0xad, 0x17, 0x58, 0x95, 0x8e,
	0x87, 0x33, 0x41, 0x05, 0x0c, 0x4b, 0x40, 0x9c, 0x9d, 0xf4, 0x67, 0x1d, 0x09, 0xaa, 0x9a, 0xce,
	0x12, 0xb8, 0x61, 0xbc, 0x3e, 0x2c, 0x0e, 0x5c, 0x8d, 0xf1, 0xe7, 0x38, 0x7e, 0xf9, 0x38, 0x75,
	0x37, 0xef, 0x70, 0x26, 0x70, 0x7f, 0xbe, 0xd7, 0x12, 0xa3, 0x7b, 0xd6, 0xe2, 0x7f, 0x63, 0x9e,
	0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xd5, 0x0e, 0x76, 0xd5, 0x0c, 0x00, 0x00,
}
